// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYNCNET_SYNCNET_H_
#define FLATBUFFERS_GENERATED_SYNCNET_SYNCNET_H_

#include "flatbuffers/flatbuffers.h"

namespace syncnet {

struct Vec3;

struct GameMessage;
struct GameMessageBuilder;

struct AddAgent;
struct AddAgentBuilder;

struct RemoveAgent;
struct RemoveAgentBuilder;

struct SetMoveTarget;
struct SetMoveTargetBuilder;

struct AgentInfo;
struct AgentInfoBuilder;

enum GameMessages {
  GameMessages_NONE = 0,
  GameMessages_AddAgent = 1,
  GameMessages_RemoveAgent = 2,
  GameMessages_SetMoveTarget = 3,
  GameMessages_AgentInfo = 4,
  GameMessages_MIN = GameMessages_NONE,
  GameMessages_MAX = GameMessages_AgentInfo
};

inline const GameMessages (&EnumValuesGameMessages())[5] {
  static const GameMessages values[] = {
    GameMessages_NONE,
    GameMessages_AddAgent,
    GameMessages_RemoveAgent,
    GameMessages_SetMoveTarget,
    GameMessages_AgentInfo
  };
  return values;
}

inline const char * const *EnumNamesGameMessages() {
  static const char * const names[6] = {
    "NONE",
    "AddAgent",
    "RemoveAgent",
    "SetMoveTarget",
    "AgentInfo",
    nullptr
  };
  return names;
}

inline const char *EnumNameGameMessages(GameMessages e) {
  if (flatbuffers::IsOutRange(e, GameMessages_NONE, GameMessages_AgentInfo)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGameMessages()[index];
}

template<typename T> struct GameMessagesTraits {
  static const GameMessages enum_value = GameMessages_NONE;
};

template<> struct GameMessagesTraits<syncnet::AddAgent> {
  static const GameMessages enum_value = GameMessages_AddAgent;
};

template<> struct GameMessagesTraits<syncnet::RemoveAgent> {
  static const GameMessages enum_value = GameMessages_RemoveAgent;
};

template<> struct GameMessagesTraits<syncnet::SetMoveTarget> {
  static const GameMessages enum_value = GameMessages_SetMoveTarget;
};

template<> struct GameMessagesTraits<syncnet::AgentInfo> {
  static const GameMessages enum_value = GameMessages_AgentInfo;
};

bool VerifyGameMessages(flatbuffers::Verifier &verifier, const void *obj, GameMessages type);
bool VerifyGameMessagesVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3() {
    memset(static_cast<void *>(this), 0, sizeof(Vec3));
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct GameMessage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GameMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG_TYPE = 4,
    VT_MSG = 6
  };
  syncnet::GameMessages msg_type() const {
    return static_cast<syncnet::GameMessages>(GetField<uint8_t>(VT_MSG_TYPE, 0));
  }
  const void *msg() const {
    return GetPointer<const void *>(VT_MSG);
  }
  template<typename T> const T *msg_as() const;
  const syncnet::AddAgent *msg_as_AddAgent() const {
    return msg_type() == syncnet::GameMessages_AddAgent ? static_cast<const syncnet::AddAgent *>(msg()) : nullptr;
  }
  const syncnet::RemoveAgent *msg_as_RemoveAgent() const {
    return msg_type() == syncnet::GameMessages_RemoveAgent ? static_cast<const syncnet::RemoveAgent *>(msg()) : nullptr;
  }
  const syncnet::SetMoveTarget *msg_as_SetMoveTarget() const {
    return msg_type() == syncnet::GameMessages_SetMoveTarget ? static_cast<const syncnet::SetMoveTarget *>(msg()) : nullptr;
  }
  const syncnet::AgentInfo *msg_as_AgentInfo() const {
    return msg_type() == syncnet::GameMessages_AgentInfo ? static_cast<const syncnet::AgentInfo *>(msg()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MSG_TYPE) &&
           VerifyOffset(verifier, VT_MSG) &&
           VerifyGameMessages(verifier, msg(), msg_type()) &&
           verifier.EndTable();
  }
};

template<> inline const syncnet::AddAgent *GameMessage::msg_as<syncnet::AddAgent>() const {
  return msg_as_AddAgent();
}

template<> inline const syncnet::RemoveAgent *GameMessage::msg_as<syncnet::RemoveAgent>() const {
  return msg_as_RemoveAgent();
}

template<> inline const syncnet::SetMoveTarget *GameMessage::msg_as<syncnet::SetMoveTarget>() const {
  return msg_as_SetMoveTarget();
}

template<> inline const syncnet::AgentInfo *GameMessage::msg_as<syncnet::AgentInfo>() const {
  return msg_as_AgentInfo();
}

struct GameMessageBuilder {
  typedef GameMessage Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_msg_type(syncnet::GameMessages msg_type) {
    fbb_.AddElement<uint8_t>(GameMessage::VT_MSG_TYPE, static_cast<uint8_t>(msg_type), 0);
  }
  void add_msg(flatbuffers::Offset<void> msg) {
    fbb_.AddOffset(GameMessage::VT_MSG, msg);
  }
  explicit GameMessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  GameMessageBuilder &operator=(const GameMessageBuilder &);
  flatbuffers::Offset<GameMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<GameMessage>(end);
    return o;
  }
};

inline flatbuffers::Offset<GameMessage> CreateGameMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    syncnet::GameMessages msg_type = syncnet::GameMessages_NONE,
    flatbuffers::Offset<void> msg = 0) {
  GameMessageBuilder builder_(_fbb);
  builder_.add_msg(msg);
  builder_.add_msg_type(msg_type);
  return builder_.Finish();
}

struct AddAgent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AddAgentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4
  };
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct AddAgentBuilder {
  typedef AddAgent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(AddAgent::VT_POS, pos);
  }
  explicit AddAgentBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AddAgentBuilder &operator=(const AddAgentBuilder &);
  flatbuffers::Offset<AddAgent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AddAgent>(end);
    return o;
  }
};

inline flatbuffers::Offset<AddAgent> CreateAddAgent(
    flatbuffers::FlatBufferBuilder &_fbb,
    const syncnet::Vec3 *pos = 0) {
  AddAgentBuilder builder_(_fbb);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct RemoveAgent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RemoveAgentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENTID = 4
  };
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           verifier.EndTable();
  }
};

struct RemoveAgentBuilder {
  typedef RemoveAgent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(RemoveAgent::VT_AGENTID, agentId, 0);
  }
  explicit RemoveAgentBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  RemoveAgentBuilder &operator=(const RemoveAgentBuilder &);
  flatbuffers::Offset<RemoveAgent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RemoveAgent>(end);
    return o;
  }
};

inline flatbuffers::Offset<RemoveAgent> CreateRemoveAgent(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t agentId = 0) {
  RemoveAgentBuilder builder_(_fbb);
  builder_.add_agentId(agentId);
  return builder_.Finish();
}

struct SetMoveTarget FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SetMoveTargetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENTID = 4,
    VT_POS = 6
  };
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct SetMoveTargetBuilder {
  typedef SetMoveTarget Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(SetMoveTarget::VT_AGENTID, agentId, 0);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(SetMoveTarget::VT_POS, pos);
  }
  explicit SetMoveTargetBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SetMoveTargetBuilder &operator=(const SetMoveTargetBuilder &);
  flatbuffers::Offset<SetMoveTarget> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SetMoveTarget>(end);
    return o;
  }
};

inline flatbuffers::Offset<SetMoveTarget> CreateSetMoveTarget(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t agentId = 0,
    const syncnet::Vec3 *pos = 0) {
  SetMoveTargetBuilder builder_(_fbb);
  builder_.add_pos(pos);
  builder_.add_agentId(agentId);
  return builder_.Finish();
}

struct AgentInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AgentInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENTID = 4,
    VT_POS = 6
  };
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct AgentInfoBuilder {
  typedef AgentInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(AgentInfo::VT_AGENTID, agentId, 0);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(AgentInfo::VT_POS, pos);
  }
  explicit AgentInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AgentInfoBuilder &operator=(const AgentInfoBuilder &);
  flatbuffers::Offset<AgentInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AgentInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<AgentInfo> CreateAgentInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t agentId = 0,
    const syncnet::Vec3 *pos = 0) {
  AgentInfoBuilder builder_(_fbb);
  builder_.add_pos(pos);
  builder_.add_agentId(agentId);
  return builder_.Finish();
}

inline bool VerifyGameMessages(flatbuffers::Verifier &verifier, const void *obj, GameMessages type) {
  switch (type) {
    case GameMessages_NONE: {
      return true;
    }
    case GameMessages_AddAgent: {
      auto ptr = reinterpret_cast<const syncnet::AddAgent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_RemoveAgent: {
      auto ptr = reinterpret_cast<const syncnet::RemoveAgent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_SetMoveTarget: {
      auto ptr = reinterpret_cast<const syncnet::SetMoveTarget *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_AgentInfo: {
      auto ptr = reinterpret_cast<const syncnet::AgentInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyGameMessagesVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyGameMessages(
        verifier,  values->Get(i), types->GetEnum<GameMessages>(i))) {
      return false;
    }
  }
  return true;
}

inline const syncnet::GameMessage *GetGameMessage(const void *buf) {
  return flatbuffers::GetRoot<syncnet::GameMessage>(buf);
}

inline const syncnet::GameMessage *GetSizePrefixedGameMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<syncnet::GameMessage>(buf);
}

inline bool VerifyGameMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<syncnet::GameMessage>(nullptr);
}

inline bool VerifySizePrefixedGameMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<syncnet::GameMessage>(nullptr);
}

inline void FinishGameMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<syncnet::GameMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGameMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<syncnet::GameMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace syncnet

#endif  // FLATBUFFERS_GENERATED_SYNCNET_SYNCNET_H_
