// Example IDL file for our monster's schema.
namespace syncnet;

union GameMessages
{ 
  AddAgent,
  RemoveAgent,
  SetMoveTarget,
  ActorInfo,
  UpdateActorNotify,
  Ping,
  SetRaycast,
  Login,
  UseSkill,
} // Optionally add more tables.

enum StatusCode:short
{
  Success = 0,
  Failed,
  NotFound,
  AlreadyExists,
}

struct Vec3 {
  x:float;
  y:float;
  z:float;
}

enum GameObjectType:byte 
{ 
  Character = 0, 
  Monster 
}

enum AIState:byte
{
  Patrol = 0,
  Detect,
  Attack,
  Dead,
  Destroyed,
}

struct ActorState {
  state:AIState;
}

struct ActorHealth {
  health:int;
}

table GameMessage {
  msg:GameMessages;
  id:int = 0;
  result:StatusCode = Success;
}

table AddAgent {
  gameObjectType:GameObjectType = Monster;
  pos:Vec3;
  agentId:int = 0;
}

table RemoveAgent {
  agentId:int;
}

table SetMoveTarget {
  agentId:int;
  pos:Vec3;
}

table ActorInfo {
  agentId:int;
  pos:Vec3;
  gameObjectType:GameObjectType = Monster;
  state:ActorState;
  health:ActorHealth;
  inputLocked:bool = false;
}

table DebugRaycast {
  startPos:Vec3;
  endPos:Vec3;
}

table UpdateActorNotify {
  actors:[ActorInfo];
  debugs:[DebugRaycast];
}

table Ping {
  seq:int;
}

table SetRaycast {
  agentId:int;
  pos:Vec3;
}

table Login {
  userId:string;
  password:string;
}

table UseSkill {
  id:int;
  skillId:int;
  targetId:int;
  pos:Vec3;
  dir:Vec3;
  timestamp:long;
  duration:long;
}

root_type GameMessage;