// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gamedata.proto
// Protobuf C++ Version: 5.29.3

#include "gamedata.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace gamedata {

inline constexpr Skill::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        effect_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        desc_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cooldown_{0},
        damage_{0},
        mana_cost_{0},
        value_{0},
        duration_{0},
        hieght_{0},
        range_{0},
        min_damage_{0},
        max_damage_{0},
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Skill::Skill(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SkillDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SkillDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SkillDefaultTypeInternal() {}
  union {
    Skill _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SkillDefaultTypeInternal _Skill_default_instance_;

inline constexpr Option::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{0},
        id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Option::Option(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OptionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OptionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OptionDefaultTypeInternal() {}
  union {
    Option _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OptionDefaultTypeInternal _Option_default_instance_;

inline constexpr SkillList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : skills_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SkillList::SkillList(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SkillListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SkillListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SkillListDefaultTypeInternal() {}
  union {
    SkillList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SkillListDefaultTypeInternal _SkillList_default_instance_;

inline constexpr Item::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : item_options_{},
        type_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        desc_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        heal_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Item::Item(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItemDefaultTypeInternal() {}
  union {
    Item _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItemDefaultTypeInternal _Item_default_instance_;

inline constexpr ItemList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : items_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ItemList::ItemList(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ItemListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItemListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItemListDefaultTypeInternal() {}
  union {
    ItemList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItemListDefaultTypeInternal _ItemList_default_instance_;
}  // namespace gamedata
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_gamedata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_gamedata_2eproto = nullptr;
const ::uint32_t
    TableStruct_gamedata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.cooldown_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.damage_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.mana_cost_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.effect_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.name_id_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.desc_id_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.duration_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.hieght_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.range_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.min_damage_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.max_damage_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Skill, _impl_.code_name_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gamedata::SkillList, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gamedata::SkillList, _impl_.skills_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gamedata::Option, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gamedata::Option, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Option, _impl_.value_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gamedata::Item, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gamedata::Item, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Item, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Item, _impl_.heal_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Item, _impl_.name_id_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Item, _impl_.desc_id_),
        PROTOBUF_FIELD_OFFSET(::gamedata::Item, _impl_.item_options_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gamedata::ItemList, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gamedata::ItemList, _impl_.items_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::gamedata::Skill)},
        {23, -1, -1, sizeof(::gamedata::SkillList)},
        {32, -1, -1, sizeof(::gamedata::Option)},
        {42, -1, -1, sizeof(::gamedata::Item)},
        {56, -1, -1, sizeof(::gamedata::ItemList)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::gamedata::_Skill_default_instance_._instance,
    &::gamedata::_SkillList_default_instance_._instance,
    &::gamedata::_Option_default_instance_._instance,
    &::gamedata::_Item_default_instance_._instance,
    &::gamedata::_ItemList_default_instance_._instance,
};
const char descriptor_table_protodef_gamedata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016gamedata.proto\022\010gamedata\"\203\002\n\005Skill\022\n\n\002"
    "id\030\001 \001(\005\022\014\n\004type\030\002 \001(\t\022\020\n\010cooldown\030\003 \001(\001"
    "\022\016\n\006damage\030\004 \001(\001\022\021\n\tmana_cost\030\005 \001(\001\022\016\n\006e"
    "ffect\030\006 \001(\t\022\r\n\005value\030\007 \001(\001\022\017\n\007name_id\030\010 "
    "\001(\t\022\017\n\007desc_id\030\t \001(\t\022\020\n\010duration\030\n \001(\001\022\016"
    "\n\006hieght\030\013 \001(\001\022\r\n\005range\030\014 \001(\001\022\022\n\nmin_dam"
    "age\030\r \001(\001\022\022\n\nmax_damage\030\016 \001(\001\022\021\n\tcode_na"
    "me\030\017 \001(\t\",\n\tSkillList\022\037\n\006skills\030\001 \003(\0132\017."
    "gamedata.Skill\"#\n\006Option\022\n\n\002id\030\001 \001(\005\022\r\n\005"
    "value\030\002 \001(\001\"x\n\004Item\022\n\n\002id\030\001 \001(\005\022\014\n\004type\030"
    "\002 \001(\t\022\014\n\004heal\030\003 \001(\005\022\017\n\007name_id\030\004 \001(\t\022\017\n\007"
    "desc_id\030\005 \001(\t\022&\n\014item_options\030\006 \003(\0132\020.ga"
    "medata.Option\")\n\010ItemList\022\035\n\005items\030\001 \003(\013"
    "2\016.gamedata.Itemb\006proto3"
};
static ::absl::once_flag descriptor_table_gamedata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_gamedata_2eproto = {
    false,
    false,
    544,
    descriptor_table_protodef_gamedata_2eproto,
    "gamedata.proto",
    &descriptor_table_gamedata_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_gamedata_2eproto::offsets,
    file_level_enum_descriptors_gamedata_2eproto,
    file_level_service_descriptors_gamedata_2eproto,
};
namespace gamedata {
// ===================================================================

class Skill::_Internal {
 public:
};

Skill::Skill(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gamedata.Skill)
}
inline PROTOBUF_NDEBUG_INLINE Skill::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::gamedata::Skill& from_msg)
      : type_(arena, from.type_),
        effect_(arena, from.effect_),
        name_id_(arena, from.name_id_),
        desc_id_(arena, from.desc_id_),
        code_name_(arena, from.code_name_),
        _cached_size_{0} {}

Skill::Skill(
    ::google::protobuf::Arena* arena,
    const Skill& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Skill* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cooldown_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, cooldown_),
           offsetof(Impl_, id_) -
               offsetof(Impl_, cooldown_) +
               sizeof(Impl_::id_));

  // @@protoc_insertion_point(copy_constructor:gamedata.Skill)
}
inline PROTOBUF_NDEBUG_INLINE Skill::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : type_(arena),
        effect_(arena),
        name_id_(arena),
        desc_id_(arena),
        code_name_(arena),
        _cached_size_{0} {}

inline void Skill::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cooldown_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, cooldown_) +
               sizeof(Impl_::id_));
}
Skill::~Skill() {
  // @@protoc_insertion_point(destructor:gamedata.Skill)
  SharedDtor(*this);
}
inline void Skill::SharedDtor(MessageLite& self) {
  Skill& this_ = static_cast<Skill&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.type_.Destroy();
  this_._impl_.effect_.Destroy();
  this_._impl_.name_id_.Destroy();
  this_._impl_.desc_id_.Destroy();
  this_._impl_.code_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Skill::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Skill(arena);
}
constexpr auto Skill::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Skill),
                                            alignof(Skill));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Skill::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Skill_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Skill::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Skill>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Skill::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Skill>(), &Skill::ByteSizeLong,
            &Skill::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Skill, _impl_._cached_size_),
        false,
    },
    &Skill::kDescriptorMethods,
    &descriptor_table_gamedata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Skill::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 15, 0, 64, 2> Skill::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    15, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294934528,  // skipmap
    offsetof(decltype(_table_), field_entries),
    15,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gamedata::Skill>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Skill, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.id_)}},
    // string type = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.type_)}},
    // double cooldown = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.cooldown_)}},
    // double damage = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.damage_)}},
    // double mana_cost = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.mana_cost_)}},
    // string effect = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.effect_)}},
    // double value = 7;
    {::_pbi::TcParser::FastF64S1,
     {57, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.value_)}},
    // string name_id = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.name_id_)}},
    // string desc_id = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.desc_id_)}},
    // double duration = 10;
    {::_pbi::TcParser::FastF64S1,
     {81, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.duration_)}},
    // double hieght = 11;
    {::_pbi::TcParser::FastF64S1,
     {89, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.hieght_)}},
    // double range = 12;
    {::_pbi::TcParser::FastF64S1,
     {97, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.range_)}},
    // double min_damage = 13;
    {::_pbi::TcParser::FastF64S1,
     {105, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.min_damage_)}},
    // double max_damage = 14;
    {::_pbi::TcParser::FastF64S1,
     {113, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.max_damage_)}},
    // string code_name = 15;
    {::_pbi::TcParser::FastUS1,
     {122, 63, 0, PROTOBUF_FIELD_OFFSET(Skill, _impl_.code_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string type = 2;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double cooldown = 3;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.cooldown_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double damage = 4;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.damage_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double mana_cost = 5;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.mana_cost_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string effect = 6;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.effect_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double value = 7;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string name_id = 8;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.name_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string desc_id = 9;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.desc_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double duration = 10;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.duration_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double hieght = 11;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.hieght_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double range = 12;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.range_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double min_damage = 13;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.min_damage_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double max_damage = 14;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.max_damage_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string code_name = 15;
    {PROTOBUF_FIELD_OFFSET(Skill, _impl_.code_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\4\0\0\0\6\0\7\7\0\0\0\0\0\11"
    "gamedata.Skill"
    "type"
    "effect"
    "name_id"
    "desc_id"
    "code_name"
  }},
};

PROTOBUF_NOINLINE void Skill::Clear() {
// @@protoc_insertion_point(message_clear_start:gamedata.Skill)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_.ClearToEmpty();
  _impl_.effect_.ClearToEmpty();
  _impl_.name_id_.ClearToEmpty();
  _impl_.desc_id_.ClearToEmpty();
  _impl_.code_name_.ClearToEmpty();
  ::memset(&_impl_.cooldown_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.id_) -
      reinterpret_cast<char*>(&_impl_.cooldown_)) + sizeof(_impl_.id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Skill::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Skill& this_ = static_cast<const Skill&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Skill::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Skill& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gamedata.Skill)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // string type = 2;
          if (!this_._internal_type().empty()) {
            const std::string& _s = this_._internal_type();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gamedata.Skill.type");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // double cooldown = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_cooldown()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_cooldown(), target);
          }

          // double damage = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_damage()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_damage(), target);
          }

          // double mana_cost = 5;
          if (::absl::bit_cast<::uint64_t>(this_._internal_mana_cost()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                5, this_._internal_mana_cost(), target);
          }

          // string effect = 6;
          if (!this_._internal_effect().empty()) {
            const std::string& _s = this_._internal_effect();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gamedata.Skill.effect");
            target = stream->WriteStringMaybeAliased(6, _s, target);
          }

          // double value = 7;
          if (::absl::bit_cast<::uint64_t>(this_._internal_value()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                7, this_._internal_value(), target);
          }

          // string name_id = 8;
          if (!this_._internal_name_id().empty()) {
            const std::string& _s = this_._internal_name_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gamedata.Skill.name_id");
            target = stream->WriteStringMaybeAliased(8, _s, target);
          }

          // string desc_id = 9;
          if (!this_._internal_desc_id().empty()) {
            const std::string& _s = this_._internal_desc_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gamedata.Skill.desc_id");
            target = stream->WriteStringMaybeAliased(9, _s, target);
          }

          // double duration = 10;
          if (::absl::bit_cast<::uint64_t>(this_._internal_duration()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                10, this_._internal_duration(), target);
          }

          // double hieght = 11;
          if (::absl::bit_cast<::uint64_t>(this_._internal_hieght()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                11, this_._internal_hieght(), target);
          }

          // double range = 12;
          if (::absl::bit_cast<::uint64_t>(this_._internal_range()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                12, this_._internal_range(), target);
          }

          // double min_damage = 13;
          if (::absl::bit_cast<::uint64_t>(this_._internal_min_damage()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                13, this_._internal_min_damage(), target);
          }

          // double max_damage = 14;
          if (::absl::bit_cast<::uint64_t>(this_._internal_max_damage()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                14, this_._internal_max_damage(), target);
          }

          // string code_name = 15;
          if (!this_._internal_code_name().empty()) {
            const std::string& _s = this_._internal_code_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gamedata.Skill.code_name");
            target = stream->WriteStringMaybeAliased(15, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gamedata.Skill)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Skill::ByteSizeLong(const MessageLite& base) {
          const Skill& this_ = static_cast<const Skill&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Skill::ByteSizeLong() const {
          const Skill& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gamedata.Skill)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string type = 2;
            if (!this_._internal_type().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_type());
            }
            // string effect = 6;
            if (!this_._internal_effect().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_effect());
            }
            // string name_id = 8;
            if (!this_._internal_name_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name_id());
            }
            // string desc_id = 9;
            if (!this_._internal_desc_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_desc_id());
            }
            // string code_name = 15;
            if (!this_._internal_code_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_code_name());
            }
            // double cooldown = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_cooldown()) != 0) {
              total_size += 9;
            }
            // double damage = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_damage()) != 0) {
              total_size += 9;
            }
            // double mana_cost = 5;
            if (::absl::bit_cast<::uint64_t>(this_._internal_mana_cost()) != 0) {
              total_size += 9;
            }
            // double value = 7;
            if (::absl::bit_cast<::uint64_t>(this_._internal_value()) != 0) {
              total_size += 9;
            }
            // double duration = 10;
            if (::absl::bit_cast<::uint64_t>(this_._internal_duration()) != 0) {
              total_size += 9;
            }
            // double hieght = 11;
            if (::absl::bit_cast<::uint64_t>(this_._internal_hieght()) != 0) {
              total_size += 9;
            }
            // double range = 12;
            if (::absl::bit_cast<::uint64_t>(this_._internal_range()) != 0) {
              total_size += 9;
            }
            // double min_damage = 13;
            if (::absl::bit_cast<::uint64_t>(this_._internal_min_damage()) != 0) {
              total_size += 9;
            }
            // double max_damage = 14;
            if (::absl::bit_cast<::uint64_t>(this_._internal_max_damage()) != 0) {
              total_size += 9;
            }
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Skill::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Skill*>(&to_msg);
  auto& from = static_cast<const Skill&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gamedata.Skill)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (!from._internal_effect().empty()) {
    _this->_internal_set_effect(from._internal_effect());
  }
  if (!from._internal_name_id().empty()) {
    _this->_internal_set_name_id(from._internal_name_id());
  }
  if (!from._internal_desc_id().empty()) {
    _this->_internal_set_desc_id(from._internal_desc_id());
  }
  if (!from._internal_code_name().empty()) {
    _this->_internal_set_code_name(from._internal_code_name());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_cooldown()) != 0) {
    _this->_impl_.cooldown_ = from._impl_.cooldown_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_damage()) != 0) {
    _this->_impl_.damage_ = from._impl_.damage_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_mana_cost()) != 0) {
    _this->_impl_.mana_cost_ = from._impl_.mana_cost_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_value()) != 0) {
    _this->_impl_.value_ = from._impl_.value_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_duration()) != 0) {
    _this->_impl_.duration_ = from._impl_.duration_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_hieght()) != 0) {
    _this->_impl_.hieght_ = from._impl_.hieght_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_range()) != 0) {
    _this->_impl_.range_ = from._impl_.range_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_min_damage()) != 0) {
    _this->_impl_.min_damage_ = from._impl_.min_damage_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_max_damage()) != 0) {
    _this->_impl_.max_damage_ = from._impl_.max_damage_;
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Skill::CopyFrom(const Skill& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamedata.Skill)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Skill::InternalSwap(Skill* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, &other->_impl_.type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.effect_, &other->_impl_.effect_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_id_, &other->_impl_.name_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_id_, &other->_impl_.desc_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.code_name_, &other->_impl_.code_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Skill, _impl_.id_)
      + sizeof(Skill::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(Skill, _impl_.cooldown_)>(
          reinterpret_cast<char*>(&_impl_.cooldown_),
          reinterpret_cast<char*>(&other->_impl_.cooldown_));
}

::google::protobuf::Metadata Skill::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SkillList::_Internal {
 public:
};

SkillList::SkillList(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gamedata.SkillList)
}
inline PROTOBUF_NDEBUG_INLINE SkillList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::gamedata::SkillList& from_msg)
      : skills_{visibility, arena, from.skills_},
        _cached_size_{0} {}

SkillList::SkillList(
    ::google::protobuf::Arena* arena,
    const SkillList& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SkillList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:gamedata.SkillList)
}
inline PROTOBUF_NDEBUG_INLINE SkillList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : skills_{visibility, arena},
        _cached_size_{0} {}

inline void SkillList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SkillList::~SkillList() {
  // @@protoc_insertion_point(destructor:gamedata.SkillList)
  SharedDtor(*this);
}
inline void SkillList::SharedDtor(MessageLite& self) {
  SkillList& this_ = static_cast<SkillList&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SkillList::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SkillList(arena);
}
constexpr auto SkillList::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SkillList, _impl_.skills_) +
          decltype(SkillList::_impl_.skills_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SkillList), alignof(SkillList), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SkillList::PlacementNew_,
                                 sizeof(SkillList),
                                 alignof(SkillList));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SkillList::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SkillList_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SkillList::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SkillList>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SkillList::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SkillList>(), &SkillList::ByteSizeLong,
            &SkillList::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SkillList, _impl_._cached_size_),
        false,
    },
    &SkillList::kDescriptorMethods,
    &descriptor_table_gamedata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SkillList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> SkillList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gamedata::SkillList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .gamedata.Skill skills = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SkillList, _impl_.skills_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .gamedata.Skill skills = 1;
    {PROTOBUF_FIELD_OFFSET(SkillList, _impl_.skills_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::gamedata::Skill>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SkillList::Clear() {
// @@protoc_insertion_point(message_clear_start:gamedata.SkillList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.skills_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SkillList::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SkillList& this_ = static_cast<const SkillList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SkillList::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SkillList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gamedata.SkillList)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .gamedata.Skill skills = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_skills_size());
               i < n; i++) {
            const auto& repfield = this_._internal_skills().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gamedata.SkillList)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SkillList::ByteSizeLong(const MessageLite& base) {
          const SkillList& this_ = static_cast<const SkillList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SkillList::ByteSizeLong() const {
          const SkillList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gamedata.SkillList)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .gamedata.Skill skills = 1;
            {
              total_size += 1UL * this_._internal_skills_size();
              for (const auto& msg : this_._internal_skills()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SkillList::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SkillList*>(&to_msg);
  auto& from = static_cast<const SkillList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gamedata.SkillList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_skills()->MergeFrom(
      from._internal_skills());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SkillList::CopyFrom(const SkillList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamedata.SkillList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SkillList::InternalSwap(SkillList* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.skills_.InternalSwap(&other->_impl_.skills_);
}

::google::protobuf::Metadata SkillList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Option::_Internal {
 public:
};

Option::Option(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gamedata.Option)
}
Option::Option(
    ::google::protobuf::Arena* arena, const Option& from)
    : Option(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Option::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Option::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, value_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, value_) +
               sizeof(Impl_::id_));
}
Option::~Option() {
  // @@protoc_insertion_point(destructor:gamedata.Option)
  SharedDtor(*this);
}
inline void Option::SharedDtor(MessageLite& self) {
  Option& this_ = static_cast<Option&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Option::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Option(arena);
}
constexpr auto Option::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Option),
                                            alignof(Option));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Option::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Option_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Option::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Option>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Option::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Option>(), &Option::ByteSizeLong,
            &Option::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Option, _impl_._cached_size_),
        false,
    },
    &Option::kDescriptorMethods,
    &descriptor_table_gamedata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Option::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Option::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gamedata::Option>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double value = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Option, _impl_.value_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Option, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Option, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Option, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // double value = 2;
    {PROTOBUF_FIELD_OFFSET(Option, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Option::Clear() {
// @@protoc_insertion_point(message_clear_start:gamedata.Option)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.value_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.id_) -
      reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Option::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Option& this_ = static_cast<const Option&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Option::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Option& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gamedata.Option)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // double value = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_value()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_value(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gamedata.Option)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Option::ByteSizeLong(const MessageLite& base) {
          const Option& this_ = static_cast<const Option&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Option::ByteSizeLong() const {
          const Option& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gamedata.Option)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double value = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_value()) != 0) {
              total_size += 9;
            }
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Option::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Option*>(&to_msg);
  auto& from = static_cast<const Option&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gamedata.Option)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_value()) != 0) {
    _this->_impl_.value_ = from._impl_.value_;
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Option::CopyFrom(const Option& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamedata.Option)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Option::InternalSwap(Option* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Option, _impl_.id_)
      + sizeof(Option::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(Option, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::google::protobuf::Metadata Option::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Item::_Internal {
 public:
};

Item::Item(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gamedata.Item)
}
inline PROTOBUF_NDEBUG_INLINE Item::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::gamedata::Item& from_msg)
      : item_options_{visibility, arena, from.item_options_},
        type_(arena, from.type_),
        name_id_(arena, from.name_id_),
        desc_id_(arena, from.desc_id_),
        _cached_size_{0} {}

Item::Item(
    ::google::protobuf::Arena* arena,
    const Item& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Item* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, heal_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::heal_));

  // @@protoc_insertion_point(copy_constructor:gamedata.Item)
}
inline PROTOBUF_NDEBUG_INLINE Item::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : item_options_{visibility, arena},
        type_(arena),
        name_id_(arena),
        desc_id_(arena),
        _cached_size_{0} {}

inline void Item::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, heal_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::heal_));
}
Item::~Item() {
  // @@protoc_insertion_point(destructor:gamedata.Item)
  SharedDtor(*this);
}
inline void Item::SharedDtor(MessageLite& self) {
  Item& this_ = static_cast<Item&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.type_.Destroy();
  this_._impl_.name_id_.Destroy();
  this_._impl_.desc_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Item::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Item(arena);
}
constexpr auto Item::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Item, _impl_.item_options_) +
          decltype(Item::_impl_.item_options_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Item), alignof(Item), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Item::PlacementNew_,
                                 sizeof(Item),
                                 alignof(Item));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Item::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Item_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Item::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Item>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Item::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Item>(), &Item::ByteSizeLong,
            &Item::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Item, _impl_._cached_size_),
        false,
    },
    &Item::kDescriptorMethods,
    &descriptor_table_gamedata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Item::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 40, 2> Item::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gamedata::Item>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Item, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Item, _impl_.id_)}},
    // string type = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Item, _impl_.type_)}},
    // int32 heal = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Item, _impl_.heal_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Item, _impl_.heal_)}},
    // string name_id = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Item, _impl_.name_id_)}},
    // string desc_id = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(Item, _impl_.desc_id_)}},
    // repeated .gamedata.Option item_options = 6;
    {::_pbi::TcParser::FastMtR1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(Item, _impl_.item_options_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Item, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string type = 2;
    {PROTOBUF_FIELD_OFFSET(Item, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 heal = 3;
    {PROTOBUF_FIELD_OFFSET(Item, _impl_.heal_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string name_id = 4;
    {PROTOBUF_FIELD_OFFSET(Item, _impl_.name_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string desc_id = 5;
    {PROTOBUF_FIELD_OFFSET(Item, _impl_.desc_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .gamedata.Option item_options = 6;
    {PROTOBUF_FIELD_OFFSET(Item, _impl_.item_options_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::gamedata::Option>()},
  }}, {{
    "\15\0\4\0\7\7\0\0"
    "gamedata.Item"
    "type"
    "name_id"
    "desc_id"
  }},
};

PROTOBUF_NOINLINE void Item::Clear() {
// @@protoc_insertion_point(message_clear_start:gamedata.Item)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.item_options_.Clear();
  _impl_.type_.ClearToEmpty();
  _impl_.name_id_.ClearToEmpty();
  _impl_.desc_id_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.heal_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.heal_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Item::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Item& this_ = static_cast<const Item&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Item::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Item& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gamedata.Item)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // string type = 2;
          if (!this_._internal_type().empty()) {
            const std::string& _s = this_._internal_type();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gamedata.Item.type");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 heal = 3;
          if (this_._internal_heal() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_heal(), target);
          }

          // string name_id = 4;
          if (!this_._internal_name_id().empty()) {
            const std::string& _s = this_._internal_name_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gamedata.Item.name_id");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string desc_id = 5;
          if (!this_._internal_desc_id().empty()) {
            const std::string& _s = this_._internal_desc_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "gamedata.Item.desc_id");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // repeated .gamedata.Option item_options = 6;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_item_options_size());
               i < n; i++) {
            const auto& repfield = this_._internal_item_options().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    6, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gamedata.Item)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Item::ByteSizeLong(const MessageLite& base) {
          const Item& this_ = static_cast<const Item&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Item::ByteSizeLong() const {
          const Item& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gamedata.Item)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .gamedata.Option item_options = 6;
            {
              total_size += 1UL * this_._internal_item_options_size();
              for (const auto& msg : this_._internal_item_options()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string type = 2;
            if (!this_._internal_type().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_type());
            }
            // string name_id = 4;
            if (!this_._internal_name_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name_id());
            }
            // string desc_id = 5;
            if (!this_._internal_desc_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_desc_id());
            }
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
            // int32 heal = 3;
            if (this_._internal_heal() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_heal());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Item::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Item*>(&to_msg);
  auto& from = static_cast<const Item&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gamedata.Item)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_item_options()->MergeFrom(
      from._internal_item_options());
  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (!from._internal_name_id().empty()) {
    _this->_internal_set_name_id(from._internal_name_id());
  }
  if (!from._internal_desc_id().empty()) {
    _this->_internal_set_desc_id(from._internal_desc_id());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_heal() != 0) {
    _this->_impl_.heal_ = from._impl_.heal_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Item::CopyFrom(const Item& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamedata.Item)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Item::InternalSwap(Item* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.item_options_.InternalSwap(&other->_impl_.item_options_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.type_, &other->_impl_.type_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_id_, &other->_impl_.name_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_id_, &other->_impl_.desc_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Item, _impl_.heal_)
      + sizeof(Item::_impl_.heal_)
      - PROTOBUF_FIELD_OFFSET(Item, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Item::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ItemList::_Internal {
 public:
};

ItemList::ItemList(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gamedata.ItemList)
}
inline PROTOBUF_NDEBUG_INLINE ItemList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::gamedata::ItemList& from_msg)
      : items_{visibility, arena, from.items_},
        _cached_size_{0} {}

ItemList::ItemList(
    ::google::protobuf::Arena* arena,
    const ItemList& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ItemList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:gamedata.ItemList)
}
inline PROTOBUF_NDEBUG_INLINE ItemList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : items_{visibility, arena},
        _cached_size_{0} {}

inline void ItemList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ItemList::~ItemList() {
  // @@protoc_insertion_point(destructor:gamedata.ItemList)
  SharedDtor(*this);
}
inline void ItemList::SharedDtor(MessageLite& self) {
  ItemList& this_ = static_cast<ItemList&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ItemList::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ItemList(arena);
}
constexpr auto ItemList::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ItemList, _impl_.items_) +
          decltype(ItemList::_impl_.items_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ItemList), alignof(ItemList), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ItemList::PlacementNew_,
                                 sizeof(ItemList),
                                 alignof(ItemList));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ItemList::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ItemList_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ItemList::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ItemList>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ItemList::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ItemList>(), &ItemList::ByteSizeLong,
            &ItemList::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ItemList, _impl_._cached_size_),
        false,
    },
    &ItemList::kDescriptorMethods,
    &descriptor_table_gamedata_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ItemList::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ItemList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gamedata::ItemList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .gamedata.Item items = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ItemList, _impl_.items_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .gamedata.Item items = 1;
    {PROTOBUF_FIELD_OFFSET(ItemList, _impl_.items_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::gamedata::Item>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ItemList::Clear() {
// @@protoc_insertion_point(message_clear_start:gamedata.ItemList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ItemList::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ItemList& this_ = static_cast<const ItemList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ItemList::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ItemList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gamedata.ItemList)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .gamedata.Item items = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_items_size());
               i < n; i++) {
            const auto& repfield = this_._internal_items().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gamedata.ItemList)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ItemList::ByteSizeLong(const MessageLite& base) {
          const ItemList& this_ = static_cast<const ItemList&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ItemList::ByteSizeLong() const {
          const ItemList& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gamedata.ItemList)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .gamedata.Item items = 1;
            {
              total_size += 1UL * this_._internal_items_size();
              for (const auto& msg : this_._internal_items()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ItemList::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ItemList*>(&to_msg);
  auto& from = static_cast<const ItemList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gamedata.ItemList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_items()->MergeFrom(
      from._internal_items());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ItemList::CopyFrom(const ItemList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamedata.ItemList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ItemList::InternalSwap(ItemList* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
}

::google::protobuf::Metadata ItemList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace gamedata
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_gamedata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
