// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ActorInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ActorInfo GetRootAsActorInfo(ByteBuffer _bb) { return GetRootAsActorInfo(_bb, new ActorInfo()); }
  public static ActorInfo GetRootAsActorInfo(ByteBuffer _bb, ActorInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ActorInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int AgentId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public syncnet.Vec3? Pos { get { int o = __p.__offset(6); return o != 0 ? (syncnet.Vec3?)(new syncnet.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public syncnet.GameObjectType GameObjectType { get { int o = __p.__offset(8); return o != 0 ? (syncnet.GameObjectType)__p.bb.GetSbyte(o + __p.bb_pos) : syncnet.GameObjectType.Monster; } }
  public syncnet.ActorState? State { get { int o = __p.__offset(10); return o != 0 ? (syncnet.ActorState?)(new syncnet.ActorState()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public syncnet.ActorHealth? Health { get { int o = __p.__offset(12); return o != 0 ? (syncnet.ActorHealth?)(new syncnet.ActorHealth()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public bool InputLocked { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static void StartActorInfo(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddAgentId(FlatBufferBuilder builder, int agentId) { builder.AddInt(0, agentId, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<syncnet.Vec3> posOffset) { builder.AddStruct(1, posOffset.Value, 0); }
  public static void AddGameObjectType(FlatBufferBuilder builder, syncnet.GameObjectType gameObjectType) { builder.AddSbyte(2, (sbyte)gameObjectType, 1); }
  public static void AddState(FlatBufferBuilder builder, Offset<syncnet.ActorState> stateOffset) { builder.AddStruct(3, stateOffset.Value, 0); }
  public static void AddHealth(FlatBufferBuilder builder, Offset<syncnet.ActorHealth> healthOffset) { builder.AddStruct(4, healthOffset.Value, 0); }
  public static void AddInputLocked(FlatBufferBuilder builder, bool inputLocked) { builder.AddBool(5, inputLocked, false); }
  public static Offset<syncnet.ActorInfo> EndActorInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.ActorInfo>(o);
  }
};


}
