// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct AddAgent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static AddAgent GetRootAsAddAgent(ByteBuffer _bb) { return GetRootAsAddAgent(_bb, new AddAgent()); }
  public static AddAgent GetRootAsAddAgent(ByteBuffer _bb, AddAgent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AddAgent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public syncnet.GameObjectType GameObjectType { get { int o = __p.__offset(4); return o != 0 ? (syncnet.GameObjectType)__p.bb.GetSbyte(o + __p.bb_pos) : syncnet.GameObjectType.Monster; } }
  public syncnet.Vec3? Pos { get { int o = __p.__offset(6); return o != 0 ? (syncnet.Vec3?)(new syncnet.Vec3()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartAddAgent(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddGameObjectType(FlatBufferBuilder builder, syncnet.GameObjectType gameObjectType) { builder.AddSbyte(0, (sbyte)gameObjectType, 1); }
  public static void AddPos(FlatBufferBuilder builder, Offset<syncnet.Vec3> posOffset) { builder.AddStruct(1, posOffset.Value, 0); }
  public static Offset<syncnet.AddAgent> EndAddAgent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.AddAgent>(o);
  }
};


}
