// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CheatCommandInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static CheatCommandInfo GetRootAsCheatCommandInfo(ByteBuffer _bb) { return GetRootAsCheatCommandInfo(_bb, new CheatCommandInfo()); }
  public static CheatCommandInfo GetRootAsCheatCommandInfo(ByteBuffer _bb, CheatCommandInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CheatCommandInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public string Args { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetArgsBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetArgsBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetArgsArray() { return __p.__vector_as_array<byte>(6); }
  public string Help { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetHelpBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetHelpBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetHelpArray() { return __p.__vector_as_array<byte>(8); }
  public string Complete { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCompleteBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetCompleteBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetCompleteArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<syncnet.CheatCommandInfo> CreateCheatCommandInfo(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      StringOffset argsOffset = default(StringOffset),
      StringOffset helpOffset = default(StringOffset),
      StringOffset completeOffset = default(StringOffset)) {
    builder.StartTable(4);
    CheatCommandInfo.AddComplete(builder, completeOffset);
    CheatCommandInfo.AddHelp(builder, helpOffset);
    CheatCommandInfo.AddArgs(builder, argsOffset);
    CheatCommandInfo.AddName(builder, nameOffset);
    return CheatCommandInfo.EndCheatCommandInfo(builder);
  }

  public static void StartCheatCommandInfo(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddArgs(FlatBufferBuilder builder, StringOffset argsOffset) { builder.AddOffset(1, argsOffset.Value, 0); }
  public static void AddHelp(FlatBufferBuilder builder, StringOffset helpOffset) { builder.AddOffset(2, helpOffset.Value, 0); }
  public static void AddComplete(FlatBufferBuilder builder, StringOffset completeOffset) { builder.AddOffset(3, completeOffset.Value, 0); }
  public static Offset<syncnet.CheatCommandInfo> EndCheatCommandInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.CheatCommandInfo>(o);
  }
};


}
