// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CheatList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static CheatList GetRootAsCheatList(ByteBuffer _bb) { return GetRootAsCheatList(_bb, new CheatList()); }
  public static CheatList GetRootAsCheatList(ByteBuffer _bb, CheatList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CheatList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public syncnet.CheatCommandInfo? Commands(int j) { int o = __p.__offset(4); return o != 0 ? (syncnet.CheatCommandInfo?)(new syncnet.CheatCommandInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CommandsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<syncnet.CheatList> CreateCheatList(FlatBufferBuilder builder,
      VectorOffset commandsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    CheatList.AddCommands(builder, commandsOffset);
    return CheatList.EndCheatList(builder);
  }

  public static void StartCheatList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCommands(FlatBufferBuilder builder, VectorOffset commandsOffset) { builder.AddOffset(0, commandsOffset.Value, 0); }
  public static VectorOffset CreateCommandsVector(FlatBufferBuilder builder, Offset<syncnet.CheatCommandInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCommandsVectorBlock(FlatBufferBuilder builder, Offset<syncnet.CheatCommandInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartCommandsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<syncnet.CheatList> EndCheatList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.CheatList>(o);
  }
};


}
