// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DialogNode : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DialogNode GetRootAsDialogNode(ByteBuffer _bb) { return GetRootAsDialogNode(_bb, new DialogNode()); }
  public static DialogNode GetRootAsDialogNode(ByteBuffer _bb, DialogNode obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DialogNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int NodeId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int NpcId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string TextId { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTextIdBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTextIdBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTextIdArray() { return __p.__vector_as_array<byte>(8); }
  public syncnet.DialogChoiceInfo? Choices(int j) { int o = __p.__offset(10); return o != 0 ? (syncnet.DialogChoiceInfo?)(new syncnet.DialogChoiceInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChoicesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<syncnet.DialogNode> CreateDialogNode(FlatBufferBuilder builder,
      int nodeId = 0,
      int npcId = 0,
      StringOffset textIdOffset = default(StringOffset),
      VectorOffset choicesOffset = default(VectorOffset)) {
    builder.StartTable(4);
    DialogNode.AddChoices(builder, choicesOffset);
    DialogNode.AddTextId(builder, textIdOffset);
    DialogNode.AddNpcId(builder, npcId);
    DialogNode.AddNodeId(builder, nodeId);
    return DialogNode.EndDialogNode(builder);
  }

  public static void StartDialogNode(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddNodeId(FlatBufferBuilder builder, int nodeId) { builder.AddInt(0, nodeId, 0); }
  public static void AddNpcId(FlatBufferBuilder builder, int npcId) { builder.AddInt(1, npcId, 0); }
  public static void AddTextId(FlatBufferBuilder builder, StringOffset textIdOffset) { builder.AddOffset(2, textIdOffset.Value, 0); }
  public static void AddChoices(FlatBufferBuilder builder, VectorOffset choicesOffset) { builder.AddOffset(3, choicesOffset.Value, 0); }
  public static VectorOffset CreateChoicesVector(FlatBufferBuilder builder, Offset<syncnet.DialogChoiceInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChoicesVectorBlock(FlatBufferBuilder builder, Offset<syncnet.DialogChoiceInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartChoicesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<syncnet.DialogNode> EndDialogNode(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.DialogNode>(o);
  }
};


}
