// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

public enum GameMessages : byte
{
  NONE = 0,
  AddAgent = 1,
  RemoveAgent = 2,
  SetMoveTarget = 3,
  AgentInfo = 4,
  GetAgents = 5,
  Ping = 6,
  SetRaycast = 7,
};


}
