// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

public enum GameMessages : byte
{
  NONE = 0,
  AddAgent = 1,
  RemoveAgent = 2,
  SetMoveTarget = 3,
  ActorInfo = 4,
  UpdateActorNotify = 5,
  Ping = 6,
  SetRaycast = 7,
  Login = 8,
  UseSkill = 9,
  TreeDebugSync = 10,
  EnterGate = 11,
  TreeDebugRequest = 12,
  Interact = 13,
  QuestAccept = 14,
  QuestComplete = 15,
  QuestAbandon = 16,
  QuestSync = 17,
  PartyInvite = 18,
  PartyInviteReply = 19,
  PartyLeave = 20,
  PartyKick = 21,
  PartyLeaderChange = 22,
  PartySync = 23,
  PartyQuestShare = 24,
  PartyQuestShareReply = 25,
  DialogNode = 26,
  DialogSelect = 27,
  PlayerStatSync = 28,
};


}
