// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

public enum GameMessages : byte
{
  NONE = 0,
  AddAgent = 1,
  RemoveAgent = 2,
  SetMoveTarget = 3,
  ActorInfo = 4,
  UpdateActorNotify = 5,
  Ping = 6,
  SetRaycast = 7,
  Login = 8,
  UseSkill = 9,
  TreeDebugSync = 10,
  EnterGate = 11,
  TreeDebugRequest = 12,
};


}
