// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

public enum GameObjectType : sbyte
{
  Character = 0,
  Monster = 1,
};


}
