// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PartyLeaderChange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PartyLeaderChange GetRootAsPartyLeaderChange(ByteBuffer _bb) { return GetRootAsPartyLeaderChange(_bb, new PartyLeaderChange()); }
  public static PartyLeaderChange GetRootAsPartyLeaderChange(ByteBuffer _bb, PartyLeaderChange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyLeaderChange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<syncnet.PartyLeaderChange> CreatePartyLeaderChange(FlatBufferBuilder builder,
      long playerId = 0) {
    builder.StartTable(1);
    PartyLeaderChange.AddPlayerId(builder, playerId);
    return PartyLeaderChange.EndPartyLeaderChange(builder);
  }

  public static void StartPartyLeaderChange(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayerId(FlatBufferBuilder builder, long playerId) { builder.AddLong(0, playerId, 0); }
  public static Offset<syncnet.PartyLeaderChange> EndPartyLeaderChange(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.PartyLeaderChange>(o);
  }
};


}
