// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PartyMemberInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PartyMemberInfo GetRootAsPartyMemberInfo(ByteBuffer _bb) { return GetRootAsPartyMemberInfo(_bb, new PartyMemberInfo()); }
  public static PartyMemberInfo GetRootAsPartyMemberInfo(ByteBuffer _bb, PartyMemberInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyMemberInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public int Level { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public int ActorId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MapId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<syncnet.PartyMemberInfo> CreatePartyMemberInfo(FlatBufferBuilder builder,
      long playerId = 0,
      StringOffset nameOffset = default(StringOffset),
      int level = 1,
      int actorId = 0,
      int mapId = 0) {
    builder.StartTable(5);
    PartyMemberInfo.AddPlayerId(builder, playerId);
    PartyMemberInfo.AddMapId(builder, mapId);
    PartyMemberInfo.AddActorId(builder, actorId);
    PartyMemberInfo.AddLevel(builder, level);
    PartyMemberInfo.AddName(builder, nameOffset);
    return PartyMemberInfo.EndPartyMemberInfo(builder);
  }

  public static void StartPartyMemberInfo(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddPlayerId(FlatBufferBuilder builder, long playerId) { builder.AddLong(0, playerId, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(2, level, 1); }
  public static void AddActorId(FlatBufferBuilder builder, int actorId) { builder.AddInt(3, actorId, 0); }
  public static void AddMapId(FlatBufferBuilder builder, int mapId) { builder.AddInt(4, mapId, 0); }
  public static Offset<syncnet.PartyMemberInfo> EndPartyMemberInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.PartyMemberInfo>(o);
  }
};


}
