// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PartyQuestShareReply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PartyQuestShareReply GetRootAsPartyQuestShareReply(ByteBuffer _bb) { return GetRootAsPartyQuestShareReply(_bb, new PartyQuestShareReply()); }
  public static PartyQuestShareReply GetRootAsPartyQuestShareReply(ByteBuffer _bb, PartyQuestShareReply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyQuestShareReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int QuestId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool Accept { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<syncnet.PartyQuestShareReply> CreatePartyQuestShareReply(FlatBufferBuilder builder,
      int questId = 0,
      bool accept = false) {
    builder.StartTable(2);
    PartyQuestShareReply.AddQuestId(builder, questId);
    PartyQuestShareReply.AddAccept(builder, accept);
    return PartyQuestShareReply.EndPartyQuestShareReply(builder);
  }

  public static void StartPartyQuestShareReply(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddQuestId(FlatBufferBuilder builder, int questId) { builder.AddInt(0, questId, 0); }
  public static void AddAccept(FlatBufferBuilder builder, bool accept) { builder.AddBool(1, accept, false); }
  public static Offset<syncnet.PartyQuestShareReply> EndPartyQuestShareReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.PartyQuestShareReply>(o);
  }
};


}
