// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PartyLeave : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PartyLeave GetRootAsPartyLeave(ByteBuffer _bb) { return GetRootAsPartyLeave(_bb, new PartyLeave()); }
  public static PartyLeave GetRootAsPartyLeave(ByteBuffer _bb, PartyLeave obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyLeave __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartPartyLeave(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<syncnet.PartyLeave> EndPartyLeave(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.PartyLeave>(o);
  }
};


}
