// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PartyQuestShare : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PartyQuestShare GetRootAsPartyQuestShare(ByteBuffer _bb) { return GetRootAsPartyQuestShare(_bb, new PartyQuestShare()); }
  public static PartyQuestShare GetRootAsPartyQuestShare(ByteBuffer _bb, PartyQuestShare obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyQuestShare __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int QuestId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long FromPlayerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string FromName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFromNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetFromNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetFromNameArray() { return __p.__vector_as_array<byte>(8); }
  public float TimeoutSec { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<syncnet.PartyQuestShare> CreatePartyQuestShare(FlatBufferBuilder builder,
      int questId = 0,
      long fromPlayerId = 0,
      StringOffset fromNameOffset = default(StringOffset),
      float timeoutSec = 0.0f) {
    builder.StartTable(4);
    PartyQuestShare.AddFromPlayerId(builder, fromPlayerId);
    PartyQuestShare.AddTimeoutSec(builder, timeoutSec);
    PartyQuestShare.AddFromName(builder, fromNameOffset);
    PartyQuestShare.AddQuestId(builder, questId);
    return PartyQuestShare.EndPartyQuestShare(builder);
  }

  public static void StartPartyQuestShare(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddQuestId(FlatBufferBuilder builder, int questId) { builder.AddInt(0, questId, 0); }
  public static void AddFromPlayerId(FlatBufferBuilder builder, long fromPlayerId) { builder.AddLong(1, fromPlayerId, 0); }
  public static void AddFromName(FlatBufferBuilder builder, StringOffset fromNameOffset) { builder.AddOffset(2, fromNameOffset.Value, 0); }
  public static void AddTimeoutSec(FlatBufferBuilder builder, float timeoutSec) { builder.AddFloat(3, timeoutSec, 0.0f); }
  public static Offset<syncnet.PartyQuestShare> EndPartyQuestShare(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.PartyQuestShare>(o);
  }
};


}
