// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PartyKick : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PartyKick GetRootAsPartyKick(ByteBuffer _bb) { return GetRootAsPartyKick(_bb, new PartyKick()); }
  public static PartyKick GetRootAsPartyKick(ByteBuffer _bb, PartyKick obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyKick __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long PlayerId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<syncnet.PartyKick> CreatePartyKick(FlatBufferBuilder builder,
      long playerId = 0) {
    builder.StartTable(1);
    PartyKick.AddPlayerId(builder, playerId);
    return PartyKick.EndPartyKick(builder);
  }

  public static void StartPartyKick(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayerId(FlatBufferBuilder builder, long playerId) { builder.AddLong(0, playerId, 0); }
  public static Offset<syncnet.PartyKick> EndPartyKick(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.PartyKick>(o);
  }
};


}
