// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PartyInviteReply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PartyInviteReply GetRootAsPartyInviteReply(ByteBuffer _bb) { return GetRootAsPartyInviteReply(_bb, new PartyInviteReply()); }
  public static PartyInviteReply GetRootAsPartyInviteReply(ByteBuffer _bb, PartyInviteReply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PartyInviteReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Accept { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<syncnet.PartyInviteReply> CreatePartyInviteReply(FlatBufferBuilder builder,
      bool accept = false) {
    builder.StartTable(1);
    PartyInviteReply.AddAccept(builder, accept);
    return PartyInviteReply.EndPartyInviteReply(builder);
  }

  public static void StartPartyInviteReply(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddAccept(FlatBufferBuilder builder, bool accept) { builder.AddBool(0, accept, false); }
  public static Offset<syncnet.PartyInviteReply> EndPartyInviteReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.PartyInviteReply>(o);
  }
};


}
