// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct PlayerStatSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static PlayerStatSync GetRootAsPlayerStatSync(ByteBuffer _bb) { return GetRootAsPlayerStatSync(_bb, new PlayerStatSync()); }
  public static PlayerStatSync GetRootAsPlayerStatSync(ByteBuffer _bb, PlayerStatSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerStatSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Level { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public long Exp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<syncnet.PlayerStatSync> CreatePlayerStatSync(FlatBufferBuilder builder,
      int level = 1,
      long exp = 0) {
    builder.StartTable(2);
    PlayerStatSync.AddExp(builder, exp);
    PlayerStatSync.AddLevel(builder, level);
    return PlayerStatSync.EndPlayerStatSync(builder);
  }

  public static void StartPlayerStatSync(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(0, level, 1); }
  public static void AddExp(FlatBufferBuilder builder, long exp) { builder.AddLong(1, exp, 0); }
  public static Offset<syncnet.PlayerStatSync> EndPlayerStatSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.PlayerStatSync>(o);
  }
};


}
