// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct QuestAbandon : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static QuestAbandon GetRootAsQuestAbandon(ByteBuffer _bb) { return GetRootAsQuestAbandon(_bb, new QuestAbandon()); }
  public static QuestAbandon GetRootAsQuestAbandon(ByteBuffer _bb, QuestAbandon obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public QuestAbandon __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int QuestId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<syncnet.QuestAbandon> CreateQuestAbandon(FlatBufferBuilder builder,
      int questId = 0) {
    builder.StartTable(1);
    QuestAbandon.AddQuestId(builder, questId);
    return QuestAbandon.EndQuestAbandon(builder);
  }

  public static void StartQuestAbandon(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddQuestId(FlatBufferBuilder builder, int questId) { builder.AddInt(0, questId, 0); }
  public static Offset<syncnet.QuestAbandon> EndQuestAbandon(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.QuestAbandon>(o);
  }
};


}
