// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct QuestSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static QuestSync GetRootAsQuestSync(ByteBuffer _bb) { return GetRootAsQuestSync(_bb, new QuestSync()); }
  public static QuestSync GetRootAsQuestSync(ByteBuffer _bb, QuestSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public QuestSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public syncnet.QuestInfo? Quests(int j) { int o = __p.__offset(4); return o != 0 ? (syncnet.QuestInfo?)(new syncnet.QuestInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int QuestsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Removed(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int RemovedLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetRemovedBytes() { return __p.__vector_as_span<int>(6, 4); }
#else
  public ArraySegment<byte>? GetRemovedBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetRemovedArray() { return __p.__vector_as_array<int>(6); }
  public int Completed(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int CompletedLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetCompletedBytes() { return __p.__vector_as_span<int>(8, 4); }
#else
  public ArraySegment<byte>? GetCompletedBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public int[] GetCompletedArray() { return __p.__vector_as_array<int>(8); }

  public static Offset<syncnet.QuestSync> CreateQuestSync(FlatBufferBuilder builder,
      VectorOffset questsOffset = default(VectorOffset),
      VectorOffset removedOffset = default(VectorOffset),
      VectorOffset completedOffset = default(VectorOffset)) {
    builder.StartTable(3);
    QuestSync.AddCompleted(builder, completedOffset);
    QuestSync.AddRemoved(builder, removedOffset);
    QuestSync.AddQuests(builder, questsOffset);
    return QuestSync.EndQuestSync(builder);
  }

  public static void StartQuestSync(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddQuests(FlatBufferBuilder builder, VectorOffset questsOffset) { builder.AddOffset(0, questsOffset.Value, 0); }
  public static VectorOffset CreateQuestsVector(FlatBufferBuilder builder, Offset<syncnet.QuestInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateQuestsVectorBlock(FlatBufferBuilder builder, Offset<syncnet.QuestInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartQuestsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRemoved(FlatBufferBuilder builder, VectorOffset removedOffset) { builder.AddOffset(1, removedOffset.Value, 0); }
  public static VectorOffset CreateRemovedVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRemovedVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartRemovedVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddCompleted(FlatBufferBuilder builder, VectorOffset completedOffset) { builder.AddOffset(2, completedOffset.Value, 0); }
  public static VectorOffset CreateCompletedVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateCompletedVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartCompletedVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<syncnet.QuestSync> EndQuestSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.QuestSync>(o);
  }
};


}
