// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct QuestAccept : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static QuestAccept GetRootAsQuestAccept(ByteBuffer _bb) { return GetRootAsQuestAccept(_bb, new QuestAccept()); }
  public static QuestAccept GetRootAsQuestAccept(ByteBuffer _bb, QuestAccept obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public QuestAccept __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int QuestId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<syncnet.QuestAccept> CreateQuestAccept(FlatBufferBuilder builder,
      int questId = 0) {
    builder.StartTable(1);
    QuestAccept.AddQuestId(builder, questId);
    return QuestAccept.EndQuestAccept(builder);
  }

  public static void StartQuestAccept(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddQuestId(FlatBufferBuilder builder, int questId) { builder.AddInt(0, questId, 0); }
  public static Offset<syncnet.QuestAccept> EndQuestAccept(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.QuestAccept>(o);
  }
};


}
