// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct QuestInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static QuestInfo GetRootAsQuestInfo(ByteBuffer _bb) { return GetRootAsQuestInfo(_bb, new QuestInfo()); }
  public static QuestInfo GetRootAsQuestInfo(ByteBuffer _bb, QuestInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public QuestInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int QuestId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public sbyte State { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public int Stage { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Progress(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ProgressLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetProgressBytes() { return __p.__vector_as_span<int>(10, 4); }
#else
  public ArraySegment<byte>? GetProgressBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public int[] GetProgressArray() { return __p.__vector_as_array<int>(10); }

  public static Offset<syncnet.QuestInfo> CreateQuestInfo(FlatBufferBuilder builder,
      int questId = 0,
      sbyte state = 0,
      int stage = 0,
      VectorOffset progressOffset = default(VectorOffset)) {
    builder.StartTable(4);
    QuestInfo.AddProgress(builder, progressOffset);
    QuestInfo.AddStage(builder, stage);
    QuestInfo.AddQuestId(builder, questId);
    QuestInfo.AddState(builder, state);
    return QuestInfo.EndQuestInfo(builder);
  }

  public static void StartQuestInfo(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddQuestId(FlatBufferBuilder builder, int questId) { builder.AddInt(0, questId, 0); }
  public static void AddState(FlatBufferBuilder builder, sbyte state) { builder.AddSbyte(1, state, 0); }
  public static void AddStage(FlatBufferBuilder builder, int stage) { builder.AddInt(2, stage, 0); }
  public static void AddProgress(FlatBufferBuilder builder, VectorOffset progressOffset) { builder.AddOffset(3, progressOffset.Value, 0); }
  public static VectorOffset CreateProgressVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateProgressVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartProgressVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<syncnet.QuestInfo> EndQuestInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.QuestInfo>(o);
  }
};


}
