// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

public enum StatusCode : short
{
  Success = 0,
  Failed = 1,
  NotFound = 2,
  AlreadyExists = 3,
};


}
