// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

public enum TreeNodeStatus : sbyte
{
  Idle = 0,
  Running = 1,
  Success = 2,
  Failure = 3,
  Skipped = 4,
  Unknown = 5,
};


}
