// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TreeDebugDefinition : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TreeDebugDefinition GetRootAsTreeDebugDefinition(ByteBuffer _bb) { return GetRootAsTreeDebugDefinition(_bb, new TreeDebugDefinition()); }
  public static TreeDebugDefinition GetRootAsTreeDebugDefinition(ByteBuffer _bb, TreeDebugDefinition obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TreeDebugDefinition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string TreeId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTreeIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTreeIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTreeIdArray() { return __p.__vector_as_array<byte>(4); }
  public long MonsterId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public syncnet.TreeDebugNodeDefinition? Nodes(int j) { int o = __p.__offset(8); return o != 0 ? (syncnet.TreeDebugNodeDefinition?)(new syncnet.TreeDebugNodeDefinition()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int NodesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<syncnet.TreeDebugDefinition> CreateTreeDebugDefinition(FlatBufferBuilder builder,
      StringOffset treeIdOffset = default(StringOffset),
      long monsterId = 0,
      VectorOffset nodesOffset = default(VectorOffset)) {
    builder.StartTable(3);
    TreeDebugDefinition.AddMonsterId(builder, monsterId);
    TreeDebugDefinition.AddNodes(builder, nodesOffset);
    TreeDebugDefinition.AddTreeId(builder, treeIdOffset);
    return TreeDebugDefinition.EndTreeDebugDefinition(builder);
  }

  public static void StartTreeDebugDefinition(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddTreeId(FlatBufferBuilder builder, StringOffset treeIdOffset) { builder.AddOffset(0, treeIdOffset.Value, 0); }
  public static void AddMonsterId(FlatBufferBuilder builder, long monsterId) { builder.AddLong(1, monsterId, 0); }
  public static void AddNodes(FlatBufferBuilder builder, VectorOffset nodesOffset) { builder.AddOffset(2, nodesOffset.Value, 0); }
  public static VectorOffset CreateNodesVector(FlatBufferBuilder builder, Offset<syncnet.TreeDebugNodeDefinition>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateNodesVectorBlock(FlatBufferBuilder builder, Offset<syncnet.TreeDebugNodeDefinition>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartNodesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<syncnet.TreeDebugDefinition> EndTreeDebugDefinition(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.TreeDebugDefinition>(o);
  }
};


}
