// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TreeDebugNodeChange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TreeDebugNodeChange GetRootAsTreeDebugNodeChange(ByteBuffer _bb) { return GetRootAsTreeDebugNodeChange(_bb, new TreeDebugNodeChange()); }
  public static TreeDebugNodeChange GetRootAsTreeDebugNodeChange(ByteBuffer _bb, TreeDebugNodeChange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TreeDebugNodeChange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort NodeId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public syncnet.TreeNodeStatus Status { get { int o = __p.__offset(8); return o != 0 ? (syncnet.TreeNodeStatus)__p.bb.GetSbyte(o + __p.bb_pos) : syncnet.TreeNodeStatus.Idle; } }
  public string Reason { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReasonBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetReasonBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetReasonArray() { return __p.__vector_as_array<byte>(10); }
  public uint SuccessCount { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint FailureCount { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RunningCount { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<syncnet.TreeDebugNodeChange> CreateTreeDebugNodeChange(FlatBufferBuilder builder,
      ushort nodeId = 0,
      StringOffset nameOffset = default(StringOffset),
      syncnet.TreeNodeStatus status = syncnet.TreeNodeStatus.Idle,
      StringOffset reasonOffset = default(StringOffset),
      uint successCount = 0,
      uint failureCount = 0,
      uint runningCount = 0) {
    builder.StartTable(7);
    TreeDebugNodeChange.AddRunningCount(builder, runningCount);
    TreeDebugNodeChange.AddFailureCount(builder, failureCount);
    TreeDebugNodeChange.AddSuccessCount(builder, successCount);
    TreeDebugNodeChange.AddReason(builder, reasonOffset);
    TreeDebugNodeChange.AddName(builder, nameOffset);
    TreeDebugNodeChange.AddNodeId(builder, nodeId);
    TreeDebugNodeChange.AddStatus(builder, status);
    return TreeDebugNodeChange.EndTreeDebugNodeChange(builder);
  }

  public static void StartTreeDebugNodeChange(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddNodeId(FlatBufferBuilder builder, ushort nodeId) { builder.AddUshort(0, nodeId, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddStatus(FlatBufferBuilder builder, syncnet.TreeNodeStatus status) { builder.AddSbyte(2, (sbyte)status, 0); }
  public static void AddReason(FlatBufferBuilder builder, StringOffset reasonOffset) { builder.AddOffset(3, reasonOffset.Value, 0); }
  public static void AddSuccessCount(FlatBufferBuilder builder, uint successCount) { builder.AddUint(4, successCount, 0); }
  public static void AddFailureCount(FlatBufferBuilder builder, uint failureCount) { builder.AddUint(5, failureCount, 0); }
  public static void AddRunningCount(FlatBufferBuilder builder, uint runningCount) { builder.AddUint(6, runningCount, 0); }
  public static Offset<syncnet.TreeDebugNodeChange> EndTreeDebugNodeChange(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.TreeDebugNodeChange>(o);
  }
};


}
