// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TreeDebugRuntimeFrame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TreeDebugRuntimeFrame GetRootAsTreeDebugRuntimeFrame(ByteBuffer _bb) { return GetRootAsTreeDebugRuntimeFrame(_bb, new TreeDebugRuntimeFrame()); }
  public static TreeDebugRuntimeFrame GetRootAsTreeDebugRuntimeFrame(ByteBuffer _bb, TreeDebugRuntimeFrame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TreeDebugRuntimeFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string TreeId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTreeIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTreeIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTreeIdArray() { return __p.__vector_as_array<byte>(4); }
  public long MonsterId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public ulong Tick { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public syncnet.AIState AiState { get { int o = __p.__offset(10); return o != 0 ? (syncnet.AIState)__p.bb.GetSbyte(o + __p.bb_pos) : syncnet.AIState.Patrol; } }
  public long TargetAgentId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)-1; } }
  public ushort ExecutedPath(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUshort(__p.__vector(o) + j * 2) : (ushort)0; }
  public int ExecutedPathLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<ushort> GetExecutedPathBytes() { return __p.__vector_as_span<ushort>(14, 2); }
#else
  public ArraySegment<byte>? GetExecutedPathBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public ushort[] GetExecutedPathArray() { return __p.__vector_as_array<ushort>(14); }
  public syncnet.TreeDebugNodeChange? Changes(int j) { int o = __p.__offset(16); return o != 0 ? (syncnet.TreeDebugNodeChange?)(new syncnet.TreeDebugNodeChange()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChangesLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<syncnet.TreeDebugRuntimeFrame> CreateTreeDebugRuntimeFrame(FlatBufferBuilder builder,
      StringOffset treeIdOffset = default(StringOffset),
      long monsterId = 0,
      ulong tick = 0,
      syncnet.AIState aiState = syncnet.AIState.Patrol,
      long targetAgentId = -1,
      VectorOffset executedPathOffset = default(VectorOffset),
      VectorOffset changesOffset = default(VectorOffset)) {
    builder.StartTable(7);
    TreeDebugRuntimeFrame.AddTargetAgentId(builder, targetAgentId);
    TreeDebugRuntimeFrame.AddTick(builder, tick);
    TreeDebugRuntimeFrame.AddMonsterId(builder, monsterId);
    TreeDebugRuntimeFrame.AddChanges(builder, changesOffset);
    TreeDebugRuntimeFrame.AddExecutedPath(builder, executedPathOffset);
    TreeDebugRuntimeFrame.AddTreeId(builder, treeIdOffset);
    TreeDebugRuntimeFrame.AddAiState(builder, aiState);
    return TreeDebugRuntimeFrame.EndTreeDebugRuntimeFrame(builder);
  }

  public static void StartTreeDebugRuntimeFrame(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddTreeId(FlatBufferBuilder builder, StringOffset treeIdOffset) { builder.AddOffset(0, treeIdOffset.Value, 0); }
  public static void AddMonsterId(FlatBufferBuilder builder, long monsterId) { builder.AddLong(1, monsterId, 0); }
  public static void AddTick(FlatBufferBuilder builder, ulong tick) { builder.AddUlong(2, tick, 0); }
  public static void AddAiState(FlatBufferBuilder builder, syncnet.AIState aiState) { builder.AddSbyte(3, (sbyte)aiState, 0); }
  public static void AddTargetAgentId(FlatBufferBuilder builder, long targetAgentId) { builder.AddLong(4, targetAgentId, -1); }
  public static void AddExecutedPath(FlatBufferBuilder builder, VectorOffset executedPathOffset) { builder.AddOffset(5, executedPathOffset.Value, 0); }
  public static VectorOffset CreateExecutedPathVector(FlatBufferBuilder builder, ushort[] data) { builder.StartVector(2, data.Length, 2); for (int i = data.Length - 1; i >= 0; i--) builder.AddUshort(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateExecutedPathVectorBlock(FlatBufferBuilder builder, ushort[] data) { builder.StartVector(2, data.Length, 2); builder.Add(data); return builder.EndVector(); }
  public static void StartExecutedPathVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(2, numElems, 2); }
  public static void AddChanges(FlatBufferBuilder builder, VectorOffset changesOffset) { builder.AddOffset(6, changesOffset.Value, 0); }
  public static VectorOffset CreateChangesVector(FlatBufferBuilder builder, Offset<syncnet.TreeDebugNodeChange>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChangesVectorBlock(FlatBufferBuilder builder, Offset<syncnet.TreeDebugNodeChange>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartChangesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<syncnet.TreeDebugRuntimeFrame> EndTreeDebugRuntimeFrame(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.TreeDebugRuntimeFrame>(o);
  }
};


}
