// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TreeDebugSync : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TreeDebugSync GetRootAsTreeDebugSync(ByteBuffer _bb) { return GetRootAsTreeDebugSync(_bb, new TreeDebugSync()); }
  public static TreeDebugSync GetRootAsTreeDebugSync(ByteBuffer _bb, TreeDebugSync obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TreeDebugSync __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public syncnet.TreeDebugDefinition? Definitions(int j) { int o = __p.__offset(4); return o != 0 ? (syncnet.TreeDebugDefinition?)(new syncnet.TreeDebugDefinition()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DefinitionsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public syncnet.TreeDebugRuntimeFrame? Frames(int j) { int o = __p.__offset(6); return o != 0 ? (syncnet.TreeDebugRuntimeFrame?)(new syncnet.TreeDebugRuntimeFrame()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FramesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<syncnet.TreeDebugSync> CreateTreeDebugSync(FlatBufferBuilder builder,
      VectorOffset definitionsOffset = default(VectorOffset),
      VectorOffset framesOffset = default(VectorOffset)) {
    builder.StartTable(2);
    TreeDebugSync.AddFrames(builder, framesOffset);
    TreeDebugSync.AddDefinitions(builder, definitionsOffset);
    return TreeDebugSync.EndTreeDebugSync(builder);
  }

  public static void StartTreeDebugSync(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDefinitions(FlatBufferBuilder builder, VectorOffset definitionsOffset) { builder.AddOffset(0, definitionsOffset.Value, 0); }
  public static VectorOffset CreateDefinitionsVector(FlatBufferBuilder builder, Offset<syncnet.TreeDebugDefinition>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDefinitionsVectorBlock(FlatBufferBuilder builder, Offset<syncnet.TreeDebugDefinition>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDefinitionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddFrames(FlatBufferBuilder builder, VectorOffset framesOffset) { builder.AddOffset(1, framesOffset.Value, 0); }
  public static VectorOffset CreateFramesVector(FlatBufferBuilder builder, Offset<syncnet.TreeDebugRuntimeFrame>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFramesVectorBlock(FlatBufferBuilder builder, Offset<syncnet.TreeDebugRuntimeFrame>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartFramesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<syncnet.TreeDebugSync> EndTreeDebugSync(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.TreeDebugSync>(o);
  }
};


}
