// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TreeDebugNodeDefinition : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TreeDebugNodeDefinition GetRootAsTreeDebugNodeDefinition(ByteBuffer _bb) { return GetRootAsTreeDebugNodeDefinition(_bb, new TreeDebugNodeDefinition()); }
  public static TreeDebugNodeDefinition GetRootAsTreeDebugNodeDefinition(ByteBuffer _bb, TreeDebugNodeDefinition obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TreeDebugNodeDefinition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort NodeId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public int ParentNodeId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(8); }
  public syncnet.TreeNodeType NodeType { get { int o = __p.__offset(10); return o != 0 ? (syncnet.TreeNodeType)__p.bb.GetSbyte(o + __p.bb_pos) : syncnet.TreeNodeType.Action; } }

  public static Offset<syncnet.TreeDebugNodeDefinition> CreateTreeDebugNodeDefinition(FlatBufferBuilder builder,
      ushort nodeId = 0,
      int parentNodeId = -1,
      StringOffset nameOffset = default(StringOffset),
      syncnet.TreeNodeType nodeType = syncnet.TreeNodeType.Action) {
    builder.StartTable(4);
    TreeDebugNodeDefinition.AddName(builder, nameOffset);
    TreeDebugNodeDefinition.AddParentNodeId(builder, parentNodeId);
    TreeDebugNodeDefinition.AddNodeId(builder, nodeId);
    TreeDebugNodeDefinition.AddNodeType(builder, nodeType);
    return TreeDebugNodeDefinition.EndTreeDebugNodeDefinition(builder);
  }

  public static void StartTreeDebugNodeDefinition(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddNodeId(FlatBufferBuilder builder, ushort nodeId) { builder.AddUshort(0, nodeId, 0); }
  public static void AddParentNodeId(FlatBufferBuilder builder, int parentNodeId) { builder.AddInt(1, parentNodeId, -1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static void AddNodeType(FlatBufferBuilder builder, syncnet.TreeNodeType nodeType) { builder.AddSbyte(3, (sbyte)nodeType, 2); }
  public static Offset<syncnet.TreeDebugNodeDefinition> EndTreeDebugNodeDefinition(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<syncnet.TreeDebugNodeDefinition>(o);
  }
};


}
