// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace syncnet
{

public enum TreeNodeType : sbyte
{
  Control = 0,
  Condition = 1,
  Action = 2,
};


}
