// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SYNCNET_SYNCNET_H_
#define FLATBUFFERS_GENERATED_SYNCNET_SYNCNET_H_

#include "flatbuffers/flatbuffers.h"

namespace syncnet {

struct Vec3;

struct ActorState;

struct ActorHealth;

struct GameMessage;
struct GameMessageBuilder;

struct AddAgent;
struct AddAgentBuilder;

struct RemoveAgent;
struct RemoveAgentBuilder;

struct SetMoveTarget;
struct SetMoveTargetBuilder;

struct ActorInfo;
struct ActorInfoBuilder;

struct DebugRaycast;
struct DebugRaycastBuilder;

struct UpdateActorNotify;
struct UpdateActorNotifyBuilder;

struct Ping;
struct PingBuilder;

struct SetRaycast;
struct SetRaycastBuilder;

struct Login;
struct LoginBuilder;

struct UseSkill;
struct UseSkillBuilder;

struct TreeDebugNodeDefinition;
struct TreeDebugNodeDefinitionBuilder;

struct TreeDebugNodeChange;
struct TreeDebugNodeChangeBuilder;

struct TreeDebugDefinition;
struct TreeDebugDefinitionBuilder;

struct TreeDebugRuntimeFrame;
struct TreeDebugRuntimeFrameBuilder;

struct TreeDebugSync;
struct TreeDebugSyncBuilder;

struct TreeDebugRequest;
struct TreeDebugRequestBuilder;

struct EnterGate;
struct EnterGateBuilder;

enum GameMessages {
  GameMessages_NONE = 0,
  GameMessages_AddAgent = 1,
  GameMessages_RemoveAgent = 2,
  GameMessages_SetMoveTarget = 3,
  GameMessages_ActorInfo = 4,
  GameMessages_UpdateActorNotify = 5,
  GameMessages_Ping = 6,
  GameMessages_SetRaycast = 7,
  GameMessages_Login = 8,
  GameMessages_UseSkill = 9,
  GameMessages_TreeDebugSync = 10,
  GameMessages_EnterGate = 11,
  GameMessages_TreeDebugRequest = 12,
  GameMessages_MIN = GameMessages_NONE,
  GameMessages_MAX = GameMessages_TreeDebugRequest
};

inline const GameMessages (&EnumValuesGameMessages())[13] {
  static const GameMessages values[] = {
    GameMessages_NONE,
    GameMessages_AddAgent,
    GameMessages_RemoveAgent,
    GameMessages_SetMoveTarget,
    GameMessages_ActorInfo,
    GameMessages_UpdateActorNotify,
    GameMessages_Ping,
    GameMessages_SetRaycast,
    GameMessages_Login,
    GameMessages_UseSkill,
    GameMessages_TreeDebugSync,
    GameMessages_EnterGate,
    GameMessages_TreeDebugRequest
  };
  return values;
}

inline const char * const *EnumNamesGameMessages() {
  static const char * const names[14] = {
    "NONE",
    "AddAgent",
    "RemoveAgent",
    "SetMoveTarget",
    "ActorInfo",
    "UpdateActorNotify",
    "Ping",
    "SetRaycast",
    "Login",
    "UseSkill",
    "TreeDebugSync",
    "EnterGate",
    "TreeDebugRequest",
    nullptr
  };
  return names;
}

inline const char *EnumNameGameMessages(GameMessages e) {
  if (flatbuffers::IsOutRange(e, GameMessages_NONE, GameMessages_TreeDebugRequest)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGameMessages()[index];
}

template<typename T> struct GameMessagesTraits {
  static const GameMessages enum_value = GameMessages_NONE;
};

template<> struct GameMessagesTraits<syncnet::AddAgent> {
  static const GameMessages enum_value = GameMessages_AddAgent;
};

template<> struct GameMessagesTraits<syncnet::RemoveAgent> {
  static const GameMessages enum_value = GameMessages_RemoveAgent;
};

template<> struct GameMessagesTraits<syncnet::SetMoveTarget> {
  static const GameMessages enum_value = GameMessages_SetMoveTarget;
};

template<> struct GameMessagesTraits<syncnet::ActorInfo> {
  static const GameMessages enum_value = GameMessages_ActorInfo;
};

template<> struct GameMessagesTraits<syncnet::UpdateActorNotify> {
  static const GameMessages enum_value = GameMessages_UpdateActorNotify;
};

template<> struct GameMessagesTraits<syncnet::Ping> {
  static const GameMessages enum_value = GameMessages_Ping;
};

template<> struct GameMessagesTraits<syncnet::SetRaycast> {
  static const GameMessages enum_value = GameMessages_SetRaycast;
};

template<> struct GameMessagesTraits<syncnet::Login> {
  static const GameMessages enum_value = GameMessages_Login;
};

template<> struct GameMessagesTraits<syncnet::UseSkill> {
  static const GameMessages enum_value = GameMessages_UseSkill;
};

template<> struct GameMessagesTraits<syncnet::TreeDebugSync> {
  static const GameMessages enum_value = GameMessages_TreeDebugSync;
};

template<> struct GameMessagesTraits<syncnet::EnterGate> {
  static const GameMessages enum_value = GameMessages_EnterGate;
};

template<> struct GameMessagesTraits<syncnet::TreeDebugRequest> {
  static const GameMessages enum_value = GameMessages_TreeDebugRequest;
};

bool VerifyGameMessages(flatbuffers::Verifier &verifier, const void *obj, GameMessages type);
bool VerifyGameMessagesVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

enum StatusCode {
  StatusCode_Success = 0,
  StatusCode_Failed = 1,
  StatusCode_NotFound = 2,
  StatusCode_AlreadyExists = 3,
  StatusCode_MIN = StatusCode_Success,
  StatusCode_MAX = StatusCode_AlreadyExists
};

inline const StatusCode (&EnumValuesStatusCode())[4] {
  static const StatusCode values[] = {
    StatusCode_Success,
    StatusCode_Failed,
    StatusCode_NotFound,
    StatusCode_AlreadyExists
  };
  return values;
}

inline const char * const *EnumNamesStatusCode() {
  static const char * const names[5] = {
    "Success",
    "Failed",
    "NotFound",
    "AlreadyExists",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatusCode(StatusCode e) {
  if (flatbuffers::IsOutRange(e, StatusCode_Success, StatusCode_AlreadyExists)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatusCode()[index];
}

enum GameObjectType {
  GameObjectType_Character = 0,
  GameObjectType_Monster = 1,
  GameObjectType_MIN = GameObjectType_Character,
  GameObjectType_MAX = GameObjectType_Monster
};

inline const GameObjectType (&EnumValuesGameObjectType())[2] {
  static const GameObjectType values[] = {
    GameObjectType_Character,
    GameObjectType_Monster
  };
  return values;
}

inline const char * const *EnumNamesGameObjectType() {
  static const char * const names[3] = {
    "Character",
    "Monster",
    nullptr
  };
  return names;
}

inline const char *EnumNameGameObjectType(GameObjectType e) {
  if (flatbuffers::IsOutRange(e, GameObjectType_Character, GameObjectType_Monster)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGameObjectType()[index];
}

enum AIState {
  AIState_Patrol = 0,
  AIState_Detect = 1,
  AIState_Attack = 2,
  AIState_Dead = 3,
  AIState_Destroyed = 4,
  AIState_MIN = AIState_Patrol,
  AIState_MAX = AIState_Destroyed
};

inline const AIState (&EnumValuesAIState())[5] {
  static const AIState values[] = {
    AIState_Patrol,
    AIState_Detect,
    AIState_Attack,
    AIState_Dead,
    AIState_Destroyed
  };
  return values;
}

inline const char * const *EnumNamesAIState() {
  static const char * const names[6] = {
    "Patrol",
    "Detect",
    "Attack",
    "Dead",
    "Destroyed",
    nullptr
  };
  return names;
}

inline const char *EnumNameAIState(AIState e) {
  if (flatbuffers::IsOutRange(e, AIState_Patrol, AIState_Destroyed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAIState()[index];
}

enum TreeNodeStatus {
  TreeNodeStatus_Idle = 0,
  TreeNodeStatus_Running = 1,
  TreeNodeStatus_Success = 2,
  TreeNodeStatus_Failure = 3,
  TreeNodeStatus_Skipped = 4,
  TreeNodeStatus_Unknown = 5,
  TreeNodeStatus_MIN = TreeNodeStatus_Idle,
  TreeNodeStatus_MAX = TreeNodeStatus_Unknown
};

inline const TreeNodeStatus (&EnumValuesTreeNodeStatus())[6] {
  static const TreeNodeStatus values[] = {
    TreeNodeStatus_Idle,
    TreeNodeStatus_Running,
    TreeNodeStatus_Success,
    TreeNodeStatus_Failure,
    TreeNodeStatus_Skipped,
    TreeNodeStatus_Unknown
  };
  return values;
}

inline const char * const *EnumNamesTreeNodeStatus() {
  static const char * const names[7] = {
    "Idle",
    "Running",
    "Success",
    "Failure",
    "Skipped",
    "Unknown",
    nullptr
  };
  return names;
}

inline const char *EnumNameTreeNodeStatus(TreeNodeStatus e) {
  if (flatbuffers::IsOutRange(e, TreeNodeStatus_Idle, TreeNodeStatus_Unknown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTreeNodeStatus()[index];
}

enum TreeNodeType {
  TreeNodeType_Control = 0,
  TreeNodeType_Condition = 1,
  TreeNodeType_Action = 2,
  TreeNodeType_MIN = TreeNodeType_Control,
  TreeNodeType_MAX = TreeNodeType_Action
};

inline const TreeNodeType (&EnumValuesTreeNodeType())[3] {
  static const TreeNodeType values[] = {
    TreeNodeType_Control,
    TreeNodeType_Condition,
    TreeNodeType_Action
  };
  return values;
}

inline const char * const *EnumNamesTreeNodeType() {
  static const char * const names[4] = {
    "Control",
    "Condition",
    "Action",
    nullptr
  };
  return names;
}

inline const char *EnumNameTreeNodeType(TreeNodeType e) {
  if (flatbuffers::IsOutRange(e, TreeNodeType_Control, TreeNodeType_Action)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTreeNodeType()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3() {
    memset(static_cast<void *>(this), 0, sizeof(Vec3));
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) ActorState FLATBUFFERS_FINAL_CLASS {
 private:
  int8_t state_;

 public:
  ActorState() {
    memset(static_cast<void *>(this), 0, sizeof(ActorState));
  }
  ActorState(syncnet::AIState _state)
      : state_(flatbuffers::EndianScalar(static_cast<int8_t>(_state))) {
  }
  syncnet::AIState state() const {
    return static_cast<syncnet::AIState>(flatbuffers::EndianScalar(state_));
  }
};
FLATBUFFERS_STRUCT_END(ActorState, 1);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) ActorHealth FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t health_;

 public:
  ActorHealth() {
    memset(static_cast<void *>(this), 0, sizeof(ActorHealth));
  }
  ActorHealth(int32_t _health)
      : health_(flatbuffers::EndianScalar(_health)) {
  }
  int32_t health() const {
    return flatbuffers::EndianScalar(health_);
  }
};
FLATBUFFERS_STRUCT_END(ActorHealth, 4);

struct GameMessage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef GameMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MSG_TYPE = 4,
    VT_MSG = 6,
    VT_ID = 8,
    VT_RESULT = 10
  };
  syncnet::GameMessages msg_type() const {
    return static_cast<syncnet::GameMessages>(GetField<uint8_t>(VT_MSG_TYPE, 0));
  }
  const void *msg() const {
    return GetPointer<const void *>(VT_MSG);
  }
  template<typename T> const T *msg_as() const;
  const syncnet::AddAgent *msg_as_AddAgent() const {
    return msg_type() == syncnet::GameMessages_AddAgent ? static_cast<const syncnet::AddAgent *>(msg()) : nullptr;
  }
  const syncnet::RemoveAgent *msg_as_RemoveAgent() const {
    return msg_type() == syncnet::GameMessages_RemoveAgent ? static_cast<const syncnet::RemoveAgent *>(msg()) : nullptr;
  }
  const syncnet::SetMoveTarget *msg_as_SetMoveTarget() const {
    return msg_type() == syncnet::GameMessages_SetMoveTarget ? static_cast<const syncnet::SetMoveTarget *>(msg()) : nullptr;
  }
  const syncnet::ActorInfo *msg_as_ActorInfo() const {
    return msg_type() == syncnet::GameMessages_ActorInfo ? static_cast<const syncnet::ActorInfo *>(msg()) : nullptr;
  }
  const syncnet::UpdateActorNotify *msg_as_UpdateActorNotify() const {
    return msg_type() == syncnet::GameMessages_UpdateActorNotify ? static_cast<const syncnet::UpdateActorNotify *>(msg()) : nullptr;
  }
  const syncnet::Ping *msg_as_Ping() const {
    return msg_type() == syncnet::GameMessages_Ping ? static_cast<const syncnet::Ping *>(msg()) : nullptr;
  }
  const syncnet::SetRaycast *msg_as_SetRaycast() const {
    return msg_type() == syncnet::GameMessages_SetRaycast ? static_cast<const syncnet::SetRaycast *>(msg()) : nullptr;
  }
  const syncnet::Login *msg_as_Login() const {
    return msg_type() == syncnet::GameMessages_Login ? static_cast<const syncnet::Login *>(msg()) : nullptr;
  }
  const syncnet::UseSkill *msg_as_UseSkill() const {
    return msg_type() == syncnet::GameMessages_UseSkill ? static_cast<const syncnet::UseSkill *>(msg()) : nullptr;
  }
  const syncnet::TreeDebugSync *msg_as_TreeDebugSync() const {
    return msg_type() == syncnet::GameMessages_TreeDebugSync ? static_cast<const syncnet::TreeDebugSync *>(msg()) : nullptr;
  }
  const syncnet::EnterGate *msg_as_EnterGate() const {
    return msg_type() == syncnet::GameMessages_EnterGate ? static_cast<const syncnet::EnterGate *>(msg()) : nullptr;
  }
  const syncnet::TreeDebugRequest *msg_as_TreeDebugRequest() const {
    return msg_type() == syncnet::GameMessages_TreeDebugRequest ? static_cast<const syncnet::TreeDebugRequest *>(msg()) : nullptr;
  }
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  syncnet::StatusCode result() const {
    return static_cast<syncnet::StatusCode>(GetField<int16_t>(VT_RESULT, 0));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MSG_TYPE) &&
           VerifyOffset(verifier, VT_MSG) &&
           VerifyGameMessages(verifier, msg(), msg_type()) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           VerifyField<int16_t>(verifier, VT_RESULT) &&
           verifier.EndTable();
  }
};

template<> inline const syncnet::AddAgent *GameMessage::msg_as<syncnet::AddAgent>() const {
  return msg_as_AddAgent();
}

template<> inline const syncnet::RemoveAgent *GameMessage::msg_as<syncnet::RemoveAgent>() const {
  return msg_as_RemoveAgent();
}

template<> inline const syncnet::SetMoveTarget *GameMessage::msg_as<syncnet::SetMoveTarget>() const {
  return msg_as_SetMoveTarget();
}

template<> inline const syncnet::ActorInfo *GameMessage::msg_as<syncnet::ActorInfo>() const {
  return msg_as_ActorInfo();
}

template<> inline const syncnet::UpdateActorNotify *GameMessage::msg_as<syncnet::UpdateActorNotify>() const {
  return msg_as_UpdateActorNotify();
}

template<> inline const syncnet::Ping *GameMessage::msg_as<syncnet::Ping>() const {
  return msg_as_Ping();
}

template<> inline const syncnet::SetRaycast *GameMessage::msg_as<syncnet::SetRaycast>() const {
  return msg_as_SetRaycast();
}

template<> inline const syncnet::Login *GameMessage::msg_as<syncnet::Login>() const {
  return msg_as_Login();
}

template<> inline const syncnet::UseSkill *GameMessage::msg_as<syncnet::UseSkill>() const {
  return msg_as_UseSkill();
}

template<> inline const syncnet::TreeDebugSync *GameMessage::msg_as<syncnet::TreeDebugSync>() const {
  return msg_as_TreeDebugSync();
}

template<> inline const syncnet::EnterGate *GameMessage::msg_as<syncnet::EnterGate>() const {
  return msg_as_EnterGate();
}

template<> inline const syncnet::TreeDebugRequest *GameMessage::msg_as<syncnet::TreeDebugRequest>() const {
  return msg_as_TreeDebugRequest();
}

struct GameMessageBuilder {
  typedef GameMessage Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_msg_type(syncnet::GameMessages msg_type) {
    fbb_.AddElement<uint8_t>(GameMessage::VT_MSG_TYPE, static_cast<uint8_t>(msg_type), 0);
  }
  void add_msg(flatbuffers::Offset<void> msg) {
    fbb_.AddOffset(GameMessage::VT_MSG, msg);
  }
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(GameMessage::VT_ID, id, 0);
  }
  void add_result(syncnet::StatusCode result) {
    fbb_.AddElement<int16_t>(GameMessage::VT_RESULT, static_cast<int16_t>(result), 0);
  }
  explicit GameMessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  GameMessageBuilder &operator=(const GameMessageBuilder &);
  flatbuffers::Offset<GameMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<GameMessage>(end);
    return o;
  }
};

inline flatbuffers::Offset<GameMessage> CreateGameMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    syncnet::GameMessages msg_type = syncnet::GameMessages_NONE,
    flatbuffers::Offset<void> msg = 0,
    int32_t id = 0,
    syncnet::StatusCode result = syncnet::StatusCode_Success) {
  GameMessageBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_msg(msg);
  builder_.add_result(result);
  builder_.add_msg_type(msg_type);
  return builder_.Finish();
}

struct AddAgent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AddAgentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GAMEOBJECTTYPE = 4,
    VT_POS = 6,
    VT_AGENTID = 8
  };
  syncnet::GameObjectType gameObjectType() const {
    return static_cast<syncnet::GameObjectType>(GetField<int8_t>(VT_GAMEOBJECTTYPE, 1));
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_GAMEOBJECTTYPE) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           verifier.EndTable();
  }
};

struct AddAgentBuilder {
  typedef AddAgent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_gameObjectType(syncnet::GameObjectType gameObjectType) {
    fbb_.AddElement<int8_t>(AddAgent::VT_GAMEOBJECTTYPE, static_cast<int8_t>(gameObjectType), 1);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(AddAgent::VT_POS, pos);
  }
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(AddAgent::VT_AGENTID, agentId, 0);
  }
  explicit AddAgentBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AddAgentBuilder &operator=(const AddAgentBuilder &);
  flatbuffers::Offset<AddAgent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AddAgent>(end);
    return o;
  }
};

inline flatbuffers::Offset<AddAgent> CreateAddAgent(
    flatbuffers::FlatBufferBuilder &_fbb,
    syncnet::GameObjectType gameObjectType = syncnet::GameObjectType_Monster,
    const syncnet::Vec3 *pos = 0,
    int32_t agentId = 0) {
  AddAgentBuilder builder_(_fbb);
  builder_.add_agentId(agentId);
  builder_.add_pos(pos);
  builder_.add_gameObjectType(gameObjectType);
  return builder_.Finish();
}

struct RemoveAgent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RemoveAgentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENTID = 4
  };
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           verifier.EndTable();
  }
};

struct RemoveAgentBuilder {
  typedef RemoveAgent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(RemoveAgent::VT_AGENTID, agentId, 0);
  }
  explicit RemoveAgentBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  RemoveAgentBuilder &operator=(const RemoveAgentBuilder &);
  flatbuffers::Offset<RemoveAgent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RemoveAgent>(end);
    return o;
  }
};

inline flatbuffers::Offset<RemoveAgent> CreateRemoveAgent(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t agentId = 0) {
  RemoveAgentBuilder builder_(_fbb);
  builder_.add_agentId(agentId);
  return builder_.Finish();
}

struct SetMoveTarget FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SetMoveTargetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENTID = 4,
    VT_POS = 6
  };
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct SetMoveTargetBuilder {
  typedef SetMoveTarget Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(SetMoveTarget::VT_AGENTID, agentId, 0);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(SetMoveTarget::VT_POS, pos);
  }
  explicit SetMoveTargetBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SetMoveTargetBuilder &operator=(const SetMoveTargetBuilder &);
  flatbuffers::Offset<SetMoveTarget> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SetMoveTarget>(end);
    return o;
  }
};

inline flatbuffers::Offset<SetMoveTarget> CreateSetMoveTarget(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t agentId = 0,
    const syncnet::Vec3 *pos = 0) {
  SetMoveTargetBuilder builder_(_fbb);
  builder_.add_pos(pos);
  builder_.add_agentId(agentId);
  return builder_.Finish();
}

struct ActorInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ActorInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENTID = 4,
    VT_POS = 6,
    VT_GAMEOBJECTTYPE = 8,
    VT_STATE = 10,
    VT_HEALTH = 12,
    VT_INPUTLOCKED = 14
  };
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  syncnet::GameObjectType gameObjectType() const {
    return static_cast<syncnet::GameObjectType>(GetField<int8_t>(VT_GAMEOBJECTTYPE, 1));
  }
  const syncnet::ActorState *state() const {
    return GetStruct<const syncnet::ActorState *>(VT_STATE);
  }
  const syncnet::ActorHealth *health() const {
    return GetStruct<const syncnet::ActorHealth *>(VT_HEALTH);
  }
  bool inputLocked() const {
    return GetField<uint8_t>(VT_INPUTLOCKED, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           VerifyField<int8_t>(verifier, VT_GAMEOBJECTTYPE) &&
           VerifyField<syncnet::ActorState>(verifier, VT_STATE) &&
           VerifyField<syncnet::ActorHealth>(verifier, VT_HEALTH) &&
           VerifyField<uint8_t>(verifier, VT_INPUTLOCKED) &&
           verifier.EndTable();
  }
};

struct ActorInfoBuilder {
  typedef ActorInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(ActorInfo::VT_AGENTID, agentId, 0);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(ActorInfo::VT_POS, pos);
  }
  void add_gameObjectType(syncnet::GameObjectType gameObjectType) {
    fbb_.AddElement<int8_t>(ActorInfo::VT_GAMEOBJECTTYPE, static_cast<int8_t>(gameObjectType), 1);
  }
  void add_state(const syncnet::ActorState *state) {
    fbb_.AddStruct(ActorInfo::VT_STATE, state);
  }
  void add_health(const syncnet::ActorHealth *health) {
    fbb_.AddStruct(ActorInfo::VT_HEALTH, health);
  }
  void add_inputLocked(bool inputLocked) {
    fbb_.AddElement<uint8_t>(ActorInfo::VT_INPUTLOCKED, static_cast<uint8_t>(inputLocked), 0);
  }
  explicit ActorInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ActorInfoBuilder &operator=(const ActorInfoBuilder &);
  flatbuffers::Offset<ActorInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ActorInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<ActorInfo> CreateActorInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t agentId = 0,
    const syncnet::Vec3 *pos = 0,
    syncnet::GameObjectType gameObjectType = syncnet::GameObjectType_Monster,
    const syncnet::ActorState *state = 0,
    const syncnet::ActorHealth *health = 0,
    bool inputLocked = false) {
  ActorInfoBuilder builder_(_fbb);
  builder_.add_health(health);
  builder_.add_state(state);
  builder_.add_pos(pos);
  builder_.add_agentId(agentId);
  builder_.add_inputLocked(inputLocked);
  builder_.add_gameObjectType(gameObjectType);
  return builder_.Finish();
}

struct DebugRaycast FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DebugRaycastBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STARTPOS = 4,
    VT_ENDPOS = 6
  };
  const syncnet::Vec3 *startPos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_STARTPOS);
  }
  const syncnet::Vec3 *endPos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_ENDPOS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<syncnet::Vec3>(verifier, VT_STARTPOS) &&
           VerifyField<syncnet::Vec3>(verifier, VT_ENDPOS) &&
           verifier.EndTable();
  }
};

struct DebugRaycastBuilder {
  typedef DebugRaycast Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_startPos(const syncnet::Vec3 *startPos) {
    fbb_.AddStruct(DebugRaycast::VT_STARTPOS, startPos);
  }
  void add_endPos(const syncnet::Vec3 *endPos) {
    fbb_.AddStruct(DebugRaycast::VT_ENDPOS, endPos);
  }
  explicit DebugRaycastBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  DebugRaycastBuilder &operator=(const DebugRaycastBuilder &);
  flatbuffers::Offset<DebugRaycast> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<DebugRaycast>(end);
    return o;
  }
};

inline flatbuffers::Offset<DebugRaycast> CreateDebugRaycast(
    flatbuffers::FlatBufferBuilder &_fbb,
    const syncnet::Vec3 *startPos = 0,
    const syncnet::Vec3 *endPos = 0) {
  DebugRaycastBuilder builder_(_fbb);
  builder_.add_endPos(endPos);
  builder_.add_startPos(startPos);
  return builder_.Finish();
}

struct UpdateActorNotify FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UpdateActorNotifyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTORS = 4,
    VT_DEBUGS = 6
  };
  const flatbuffers::Vector<flatbuffers::Offset<syncnet::ActorInfo>> *actors() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<syncnet::ActorInfo>> *>(VT_ACTORS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<syncnet::DebugRaycast>> *debugs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<syncnet::DebugRaycast>> *>(VT_DEBUGS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACTORS) &&
           verifier.VerifyVector(actors()) &&
           verifier.VerifyVectorOfTables(actors()) &&
           VerifyOffset(verifier, VT_DEBUGS) &&
           verifier.VerifyVector(debugs()) &&
           verifier.VerifyVectorOfTables(debugs()) &&
           verifier.EndTable();
  }
};

struct UpdateActorNotifyBuilder {
  typedef UpdateActorNotify Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_actors(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::ActorInfo>>> actors) {
    fbb_.AddOffset(UpdateActorNotify::VT_ACTORS, actors);
  }
  void add_debugs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::DebugRaycast>>> debugs) {
    fbb_.AddOffset(UpdateActorNotify::VT_DEBUGS, debugs);
  }
  explicit UpdateActorNotifyBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UpdateActorNotifyBuilder &operator=(const UpdateActorNotifyBuilder &);
  flatbuffers::Offset<UpdateActorNotify> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UpdateActorNotify>(end);
    return o;
  }
};

inline flatbuffers::Offset<UpdateActorNotify> CreateUpdateActorNotify(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::ActorInfo>>> actors = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::DebugRaycast>>> debugs = 0) {
  UpdateActorNotifyBuilder builder_(_fbb);
  builder_.add_debugs(debugs);
  builder_.add_actors(actors);
  return builder_.Finish();
}

inline flatbuffers::Offset<UpdateActorNotify> CreateUpdateActorNotifyDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<syncnet::ActorInfo>> *actors = nullptr,
    const std::vector<flatbuffers::Offset<syncnet::DebugRaycast>> *debugs = nullptr) {
  auto actors__ = actors ? _fbb.CreateVector<flatbuffers::Offset<syncnet::ActorInfo>>(*actors) : 0;
  auto debugs__ = debugs ? _fbb.CreateVector<flatbuffers::Offset<syncnet::DebugRaycast>>(*debugs) : 0;
  return syncnet::CreateUpdateActorNotify(
      _fbb,
      actors__,
      debugs__);
}

struct Ping FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQ = 4
  };
  int32_t seq() const {
    return GetField<int32_t>(VT_SEQ, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SEQ) &&
           verifier.EndTable();
  }
};

struct PingBuilder {
  typedef Ping Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_seq(int32_t seq) {
    fbb_.AddElement<int32_t>(Ping::VT_SEQ, seq, 0);
  }
  explicit PingBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PingBuilder &operator=(const PingBuilder &);
  flatbuffers::Offset<Ping> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Ping>(end);
    return o;
  }
};

inline flatbuffers::Offset<Ping> CreatePing(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t seq = 0) {
  PingBuilder builder_(_fbb);
  builder_.add_seq(seq);
  return builder_.Finish();
}

struct SetRaycast FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SetRaycastBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGENTID = 4,
    VT_POS = 6
  };
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           verifier.EndTable();
  }
};

struct SetRaycastBuilder {
  typedef SetRaycast Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(SetRaycast::VT_AGENTID, agentId, 0);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(SetRaycast::VT_POS, pos);
  }
  explicit SetRaycastBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SetRaycastBuilder &operator=(const SetRaycastBuilder &);
  flatbuffers::Offset<SetRaycast> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SetRaycast>(end);
    return o;
  }
};

inline flatbuffers::Offset<SetRaycast> CreateSetRaycast(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t agentId = 0,
    const syncnet::Vec3 *pos = 0) {
  SetRaycastBuilder builder_(_fbb);
  builder_.add_pos(pos);
  builder_.add_agentId(agentId);
  return builder_.Finish();
}

struct Login FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USERID = 4,
    VT_PASSWORD = 6,
    VT_MAPID = 8,
    VT_POS = 10,
    VT_AGENTID = 12,
    VT_UUID = 14
  };
  const flatbuffers::String *userId() const {
    return GetPointer<const flatbuffers::String *>(VT_USERID);
  }
  const flatbuffers::String *password() const {
    return GetPointer<const flatbuffers::String *>(VT_PASSWORD);
  }
  int32_t mapId() const {
    return GetField<int32_t>(VT_MAPID, 0);
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  const flatbuffers::String *uuid() const {
    return GetPointer<const flatbuffers::String *>(VT_UUID);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USERID) &&
           verifier.VerifyString(userId()) &&
           VerifyOffset(verifier, VT_PASSWORD) &&
           verifier.VerifyString(password()) &&
           VerifyField<int32_t>(verifier, VT_MAPID) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           VerifyOffset(verifier, VT_UUID) &&
           verifier.VerifyString(uuid()) &&
           verifier.EndTable();
  }
};

struct LoginBuilder {
  typedef Login Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_userId(flatbuffers::Offset<flatbuffers::String> userId) {
    fbb_.AddOffset(Login::VT_USERID, userId);
  }
  void add_password(flatbuffers::Offset<flatbuffers::String> password) {
    fbb_.AddOffset(Login::VT_PASSWORD, password);
  }
  void add_mapId(int32_t mapId) {
    fbb_.AddElement<int32_t>(Login::VT_MAPID, mapId, 0);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(Login::VT_POS, pos);
  }
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(Login::VT_AGENTID, agentId, 0);
  }
  void add_uuid(flatbuffers::Offset<flatbuffers::String> uuid) {
    fbb_.AddOffset(Login::VT_UUID, uuid);
  }
  explicit LoginBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LoginBuilder &operator=(const LoginBuilder &);
  flatbuffers::Offset<Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Login>(end);
    return o;
  }
};

inline flatbuffers::Offset<Login> CreateLogin(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> userId = 0,
    flatbuffers::Offset<flatbuffers::String> password = 0,
    int32_t mapId = 0,
    const syncnet::Vec3 *pos = 0,
    int32_t agentId = 0,
    flatbuffers::Offset<flatbuffers::String> uuid = 0) {
  LoginBuilder builder_(_fbb);
  builder_.add_uuid(uuid);
  builder_.add_agentId(agentId);
  builder_.add_pos(pos);
  builder_.add_mapId(mapId);
  builder_.add_password(password);
  builder_.add_userId(userId);
  return builder_.Finish();
}

inline flatbuffers::Offset<Login> CreateLoginDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *userId = nullptr,
    const char *password = nullptr,
    int32_t mapId = 0,
    const syncnet::Vec3 *pos = 0,
    int32_t agentId = 0,
    const char *uuid = nullptr) {
  auto userId__ = userId ? _fbb.CreateString(userId) : 0;
  auto password__ = password ? _fbb.CreateString(password) : 0;
  auto uuid__ = uuid ? _fbb.CreateString(uuid) : 0;
  return syncnet::CreateLogin(
      _fbb,
      userId__,
      password__,
      mapId,
      pos,
      agentId,
      uuid__);
}

struct UseSkill FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UseSkillBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_SKILLID = 6,
    VT_TARGETID = 8,
    VT_POS = 10,
    VT_DIR = 12,
    VT_TIMESTAMP = 14,
    VT_DURATION = 16
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int32_t skillId() const {
    return GetField<int32_t>(VT_SKILLID, 0);
  }
  int32_t targetId() const {
    return GetField<int32_t>(VT_TARGETID, 0);
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  const syncnet::Vec3 *dir() const {
    return GetStruct<const syncnet::Vec3 *>(VT_DIR);
  }
  int64_t timestamp() const {
    return GetField<int64_t>(VT_TIMESTAMP, 0);
  }
  int64_t duration() const {
    return GetField<int64_t>(VT_DURATION, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           VerifyField<int32_t>(verifier, VT_SKILLID) &&
           VerifyField<int32_t>(verifier, VT_TARGETID) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           VerifyField<syncnet::Vec3>(verifier, VT_DIR) &&
           VerifyField<int64_t>(verifier, VT_TIMESTAMP) &&
           VerifyField<int64_t>(verifier, VT_DURATION) &&
           verifier.EndTable();
  }
};

struct UseSkillBuilder {
  typedef UseSkill Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(UseSkill::VT_ID, id, 0);
  }
  void add_skillId(int32_t skillId) {
    fbb_.AddElement<int32_t>(UseSkill::VT_SKILLID, skillId, 0);
  }
  void add_targetId(int32_t targetId) {
    fbb_.AddElement<int32_t>(UseSkill::VT_TARGETID, targetId, 0);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(UseSkill::VT_POS, pos);
  }
  void add_dir(const syncnet::Vec3 *dir) {
    fbb_.AddStruct(UseSkill::VT_DIR, dir);
  }
  void add_timestamp(int64_t timestamp) {
    fbb_.AddElement<int64_t>(UseSkill::VT_TIMESTAMP, timestamp, 0);
  }
  void add_duration(int64_t duration) {
    fbb_.AddElement<int64_t>(UseSkill::VT_DURATION, duration, 0);
  }
  explicit UseSkillBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  UseSkillBuilder &operator=(const UseSkillBuilder &);
  flatbuffers::Offset<UseSkill> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UseSkill>(end);
    return o;
  }
};

inline flatbuffers::Offset<UseSkill> CreateUseSkill(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int32_t skillId = 0,
    int32_t targetId = 0,
    const syncnet::Vec3 *pos = 0,
    const syncnet::Vec3 *dir = 0,
    int64_t timestamp = 0,
    int64_t duration = 0) {
  UseSkillBuilder builder_(_fbb);
  builder_.add_duration(duration);
  builder_.add_timestamp(timestamp);
  builder_.add_dir(dir);
  builder_.add_pos(pos);
  builder_.add_targetId(targetId);
  builder_.add_skillId(skillId);
  builder_.add_id(id);
  return builder_.Finish();
}

struct TreeDebugNodeDefinition FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TreeDebugNodeDefinitionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODEID = 4,
    VT_PARENTNODEID = 6,
    VT_NAME = 8,
    VT_NODETYPE = 10
  };
  uint16_t nodeId() const {
    return GetField<uint16_t>(VT_NODEID, 0);
  }
  int32_t parentNodeId() const {
    return GetField<int32_t>(VT_PARENTNODEID, -1);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  syncnet::TreeNodeType nodeType() const {
    return static_cast<syncnet::TreeNodeType>(GetField<int8_t>(VT_NODETYPE, 2));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_NODEID) &&
           VerifyField<int32_t>(verifier, VT_PARENTNODEID) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_NODETYPE) &&
           verifier.EndTable();
  }
};

struct TreeDebugNodeDefinitionBuilder {
  typedef TreeDebugNodeDefinition Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_nodeId(uint16_t nodeId) {
    fbb_.AddElement<uint16_t>(TreeDebugNodeDefinition::VT_NODEID, nodeId, 0);
  }
  void add_parentNodeId(int32_t parentNodeId) {
    fbb_.AddElement<int32_t>(TreeDebugNodeDefinition::VT_PARENTNODEID, parentNodeId, -1);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(TreeDebugNodeDefinition::VT_NAME, name);
  }
  void add_nodeType(syncnet::TreeNodeType nodeType) {
    fbb_.AddElement<int8_t>(TreeDebugNodeDefinition::VT_NODETYPE, static_cast<int8_t>(nodeType), 2);
  }
  explicit TreeDebugNodeDefinitionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TreeDebugNodeDefinitionBuilder &operator=(const TreeDebugNodeDefinitionBuilder &);
  flatbuffers::Offset<TreeDebugNodeDefinition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TreeDebugNodeDefinition>(end);
    return o;
  }
};

inline flatbuffers::Offset<TreeDebugNodeDefinition> CreateTreeDebugNodeDefinition(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t nodeId = 0,
    int32_t parentNodeId = -1,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    syncnet::TreeNodeType nodeType = syncnet::TreeNodeType_Action) {
  TreeDebugNodeDefinitionBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_parentNodeId(parentNodeId);
  builder_.add_nodeId(nodeId);
  builder_.add_nodeType(nodeType);
  return builder_.Finish();
}

inline flatbuffers::Offset<TreeDebugNodeDefinition> CreateTreeDebugNodeDefinitionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t nodeId = 0,
    int32_t parentNodeId = -1,
    const char *name = nullptr,
    syncnet::TreeNodeType nodeType = syncnet::TreeNodeType_Action) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return syncnet::CreateTreeDebugNodeDefinition(
      _fbb,
      nodeId,
      parentNodeId,
      name__,
      nodeType);
}

struct TreeDebugNodeChange FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TreeDebugNodeChangeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODEID = 4,
    VT_NAME = 6,
    VT_STATUS = 8,
    VT_REASON = 10,
    VT_SUCCESSCOUNT = 12,
    VT_FAILURECOUNT = 14,
    VT_RUNNINGCOUNT = 16
  };
  uint16_t nodeId() const {
    return GetField<uint16_t>(VT_NODEID, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  syncnet::TreeNodeStatus status() const {
    return static_cast<syncnet::TreeNodeStatus>(GetField<int8_t>(VT_STATUS, 0));
  }
  const flatbuffers::String *reason() const {
    return GetPointer<const flatbuffers::String *>(VT_REASON);
  }
  uint32_t successCount() const {
    return GetField<uint32_t>(VT_SUCCESSCOUNT, 0);
  }
  uint32_t failureCount() const {
    return GetField<uint32_t>(VT_FAILURECOUNT, 0);
  }
  uint32_t runningCount() const {
    return GetField<uint32_t>(VT_RUNNINGCOUNT, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_NODEID) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_STATUS) &&
           VerifyOffset(verifier, VT_REASON) &&
           verifier.VerifyString(reason()) &&
           VerifyField<uint32_t>(verifier, VT_SUCCESSCOUNT) &&
           VerifyField<uint32_t>(verifier, VT_FAILURECOUNT) &&
           VerifyField<uint32_t>(verifier, VT_RUNNINGCOUNT) &&
           verifier.EndTable();
  }
};

struct TreeDebugNodeChangeBuilder {
  typedef TreeDebugNodeChange Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_nodeId(uint16_t nodeId) {
    fbb_.AddElement<uint16_t>(TreeDebugNodeChange::VT_NODEID, nodeId, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(TreeDebugNodeChange::VT_NAME, name);
  }
  void add_status(syncnet::TreeNodeStatus status) {
    fbb_.AddElement<int8_t>(TreeDebugNodeChange::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_reason(flatbuffers::Offset<flatbuffers::String> reason) {
    fbb_.AddOffset(TreeDebugNodeChange::VT_REASON, reason);
  }
  void add_successCount(uint32_t successCount) {
    fbb_.AddElement<uint32_t>(TreeDebugNodeChange::VT_SUCCESSCOUNT, successCount, 0);
  }
  void add_failureCount(uint32_t failureCount) {
    fbb_.AddElement<uint32_t>(TreeDebugNodeChange::VT_FAILURECOUNT, failureCount, 0);
  }
  void add_runningCount(uint32_t runningCount) {
    fbb_.AddElement<uint32_t>(TreeDebugNodeChange::VT_RUNNINGCOUNT, runningCount, 0);
  }
  explicit TreeDebugNodeChangeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TreeDebugNodeChangeBuilder &operator=(const TreeDebugNodeChangeBuilder &);
  flatbuffers::Offset<TreeDebugNodeChange> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TreeDebugNodeChange>(end);
    return o;
  }
};

inline flatbuffers::Offset<TreeDebugNodeChange> CreateTreeDebugNodeChange(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t nodeId = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    syncnet::TreeNodeStatus status = syncnet::TreeNodeStatus_Idle,
    flatbuffers::Offset<flatbuffers::String> reason = 0,
    uint32_t successCount = 0,
    uint32_t failureCount = 0,
    uint32_t runningCount = 0) {
  TreeDebugNodeChangeBuilder builder_(_fbb);
  builder_.add_runningCount(runningCount);
  builder_.add_failureCount(failureCount);
  builder_.add_successCount(successCount);
  builder_.add_reason(reason);
  builder_.add_name(name);
  builder_.add_nodeId(nodeId);
  builder_.add_status(status);
  return builder_.Finish();
}

inline flatbuffers::Offset<TreeDebugNodeChange> CreateTreeDebugNodeChangeDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t nodeId = 0,
    const char *name = nullptr,
    syncnet::TreeNodeStatus status = syncnet::TreeNodeStatus_Idle,
    const char *reason = nullptr,
    uint32_t successCount = 0,
    uint32_t failureCount = 0,
    uint32_t runningCount = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto reason__ = reason ? _fbb.CreateString(reason) : 0;
  return syncnet::CreateTreeDebugNodeChange(
      _fbb,
      nodeId,
      name__,
      status,
      reason__,
      successCount,
      failureCount,
      runningCount);
}

struct TreeDebugDefinition FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TreeDebugDefinitionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TREEID = 4,
    VT_MONSTERID = 6,
    VT_NODES = 8
  };
  const flatbuffers::String *treeId() const {
    return GetPointer<const flatbuffers::String *>(VT_TREEID);
  }
  int64_t monsterId() const {
    return GetField<int64_t>(VT_MONSTERID, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugNodeDefinition>> *nodes() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugNodeDefinition>> *>(VT_NODES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TREEID) &&
           verifier.VerifyString(treeId()) &&
           VerifyField<int64_t>(verifier, VT_MONSTERID) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           verifier.EndTable();
  }
};

struct TreeDebugDefinitionBuilder {
  typedef TreeDebugDefinition Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_treeId(flatbuffers::Offset<flatbuffers::String> treeId) {
    fbb_.AddOffset(TreeDebugDefinition::VT_TREEID, treeId);
  }
  void add_monsterId(int64_t monsterId) {
    fbb_.AddElement<int64_t>(TreeDebugDefinition::VT_MONSTERID, monsterId, 0);
  }
  void add_nodes(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugNodeDefinition>>> nodes) {
    fbb_.AddOffset(TreeDebugDefinition::VT_NODES, nodes);
  }
  explicit TreeDebugDefinitionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TreeDebugDefinitionBuilder &operator=(const TreeDebugDefinitionBuilder &);
  flatbuffers::Offset<TreeDebugDefinition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TreeDebugDefinition>(end);
    return o;
  }
};

inline flatbuffers::Offset<TreeDebugDefinition> CreateTreeDebugDefinition(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> treeId = 0,
    int64_t monsterId = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugNodeDefinition>>> nodes = 0) {
  TreeDebugDefinitionBuilder builder_(_fbb);
  builder_.add_monsterId(monsterId);
  builder_.add_nodes(nodes);
  builder_.add_treeId(treeId);
  return builder_.Finish();
}

inline flatbuffers::Offset<TreeDebugDefinition> CreateTreeDebugDefinitionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *treeId = nullptr,
    int64_t monsterId = 0,
    const std::vector<flatbuffers::Offset<syncnet::TreeDebugNodeDefinition>> *nodes = nullptr) {
  auto treeId__ = treeId ? _fbb.CreateString(treeId) : 0;
  auto nodes__ = nodes ? _fbb.CreateVector<flatbuffers::Offset<syncnet::TreeDebugNodeDefinition>>(*nodes) : 0;
  return syncnet::CreateTreeDebugDefinition(
      _fbb,
      treeId__,
      monsterId,
      nodes__);
}

struct TreeDebugRuntimeFrame FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TreeDebugRuntimeFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TREEID = 4,
    VT_MONSTERID = 6,
    VT_TICK = 8,
    VT_AISTATE = 10,
    VT_TARGETAGENTID = 12,
    VT_EXECUTEDPATH = 14,
    VT_CHANGES = 16
  };
  const flatbuffers::String *treeId() const {
    return GetPointer<const flatbuffers::String *>(VT_TREEID);
  }
  int64_t monsterId() const {
    return GetField<int64_t>(VT_MONSTERID, 0);
  }
  uint64_t tick() const {
    return GetField<uint64_t>(VT_TICK, 0);
  }
  syncnet::AIState aiState() const {
    return static_cast<syncnet::AIState>(GetField<int8_t>(VT_AISTATE, 0));
  }
  int64_t targetAgentId() const {
    return GetField<int64_t>(VT_TARGETAGENTID, -1LL);
  }
  const flatbuffers::Vector<uint16_t> *executedPath() const {
    return GetPointer<const flatbuffers::Vector<uint16_t> *>(VT_EXECUTEDPATH);
  }
  const flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugNodeChange>> *changes() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugNodeChange>> *>(VT_CHANGES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TREEID) &&
           verifier.VerifyString(treeId()) &&
           VerifyField<int64_t>(verifier, VT_MONSTERID) &&
           VerifyField<uint64_t>(verifier, VT_TICK) &&
           VerifyField<int8_t>(verifier, VT_AISTATE) &&
           VerifyField<int64_t>(verifier, VT_TARGETAGENTID) &&
           VerifyOffset(verifier, VT_EXECUTEDPATH) &&
           verifier.VerifyVector(executedPath()) &&
           VerifyOffset(verifier, VT_CHANGES) &&
           verifier.VerifyVector(changes()) &&
           verifier.VerifyVectorOfTables(changes()) &&
           verifier.EndTable();
  }
};

struct TreeDebugRuntimeFrameBuilder {
  typedef TreeDebugRuntimeFrame Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_treeId(flatbuffers::Offset<flatbuffers::String> treeId) {
    fbb_.AddOffset(TreeDebugRuntimeFrame::VT_TREEID, treeId);
  }
  void add_monsterId(int64_t monsterId) {
    fbb_.AddElement<int64_t>(TreeDebugRuntimeFrame::VT_MONSTERID, monsterId, 0);
  }
  void add_tick(uint64_t tick) {
    fbb_.AddElement<uint64_t>(TreeDebugRuntimeFrame::VT_TICK, tick, 0);
  }
  void add_aiState(syncnet::AIState aiState) {
    fbb_.AddElement<int8_t>(TreeDebugRuntimeFrame::VT_AISTATE, static_cast<int8_t>(aiState), 0);
  }
  void add_targetAgentId(int64_t targetAgentId) {
    fbb_.AddElement<int64_t>(TreeDebugRuntimeFrame::VT_TARGETAGENTID, targetAgentId, -1LL);
  }
  void add_executedPath(flatbuffers::Offset<flatbuffers::Vector<uint16_t>> executedPath) {
    fbb_.AddOffset(TreeDebugRuntimeFrame::VT_EXECUTEDPATH, executedPath);
  }
  void add_changes(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugNodeChange>>> changes) {
    fbb_.AddOffset(TreeDebugRuntimeFrame::VT_CHANGES, changes);
  }
  explicit TreeDebugRuntimeFrameBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TreeDebugRuntimeFrameBuilder &operator=(const TreeDebugRuntimeFrameBuilder &);
  flatbuffers::Offset<TreeDebugRuntimeFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TreeDebugRuntimeFrame>(end);
    return o;
  }
};

inline flatbuffers::Offset<TreeDebugRuntimeFrame> CreateTreeDebugRuntimeFrame(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> treeId = 0,
    int64_t monsterId = 0,
    uint64_t tick = 0,
    syncnet::AIState aiState = syncnet::AIState_Patrol,
    int64_t targetAgentId = -1LL,
    flatbuffers::Offset<flatbuffers::Vector<uint16_t>> executedPath = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugNodeChange>>> changes = 0) {
  TreeDebugRuntimeFrameBuilder builder_(_fbb);
  builder_.add_targetAgentId(targetAgentId);
  builder_.add_tick(tick);
  builder_.add_monsterId(monsterId);
  builder_.add_changes(changes);
  builder_.add_executedPath(executedPath);
  builder_.add_treeId(treeId);
  builder_.add_aiState(aiState);
  return builder_.Finish();
}

inline flatbuffers::Offset<TreeDebugRuntimeFrame> CreateTreeDebugRuntimeFrameDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *treeId = nullptr,
    int64_t monsterId = 0,
    uint64_t tick = 0,
    syncnet::AIState aiState = syncnet::AIState_Patrol,
    int64_t targetAgentId = -1LL,
    const std::vector<uint16_t> *executedPath = nullptr,
    const std::vector<flatbuffers::Offset<syncnet::TreeDebugNodeChange>> *changes = nullptr) {
  auto treeId__ = treeId ? _fbb.CreateString(treeId) : 0;
  auto executedPath__ = executedPath ? _fbb.CreateVector<uint16_t>(*executedPath) : 0;
  auto changes__ = changes ? _fbb.CreateVector<flatbuffers::Offset<syncnet::TreeDebugNodeChange>>(*changes) : 0;
  return syncnet::CreateTreeDebugRuntimeFrame(
      _fbb,
      treeId__,
      monsterId,
      tick,
      aiState,
      targetAgentId,
      executedPath__,
      changes__);
}

struct TreeDebugSync FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TreeDebugSyncBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEFINITIONS = 4,
    VT_FRAMES = 6
  };
  const flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugDefinition>> *definitions() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugDefinition>> *>(VT_DEFINITIONS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugRuntimeFrame>> *frames() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugRuntimeFrame>> *>(VT_FRAMES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DEFINITIONS) &&
           verifier.VerifyVector(definitions()) &&
           verifier.VerifyVectorOfTables(definitions()) &&
           VerifyOffset(verifier, VT_FRAMES) &&
           verifier.VerifyVector(frames()) &&
           verifier.VerifyVectorOfTables(frames()) &&
           verifier.EndTable();
  }
};

struct TreeDebugSyncBuilder {
  typedef TreeDebugSync Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_definitions(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugDefinition>>> definitions) {
    fbb_.AddOffset(TreeDebugSync::VT_DEFINITIONS, definitions);
  }
  void add_frames(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugRuntimeFrame>>> frames) {
    fbb_.AddOffset(TreeDebugSync::VT_FRAMES, frames);
  }
  explicit TreeDebugSyncBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TreeDebugSyncBuilder &operator=(const TreeDebugSyncBuilder &);
  flatbuffers::Offset<TreeDebugSync> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TreeDebugSync>(end);
    return o;
  }
};

inline flatbuffers::Offset<TreeDebugSync> CreateTreeDebugSync(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugDefinition>>> definitions = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<syncnet::TreeDebugRuntimeFrame>>> frames = 0) {
  TreeDebugSyncBuilder builder_(_fbb);
  builder_.add_frames(frames);
  builder_.add_definitions(definitions);
  return builder_.Finish();
}

inline flatbuffers::Offset<TreeDebugSync> CreateTreeDebugSyncDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<syncnet::TreeDebugDefinition>> *definitions = nullptr,
    const std::vector<flatbuffers::Offset<syncnet::TreeDebugRuntimeFrame>> *frames = nullptr) {
  auto definitions__ = definitions ? _fbb.CreateVector<flatbuffers::Offset<syncnet::TreeDebugDefinition>>(*definitions) : 0;
  auto frames__ = frames ? _fbb.CreateVector<flatbuffers::Offset<syncnet::TreeDebugRuntimeFrame>>(*frames) : 0;
  return syncnet::CreateTreeDebugSync(
      _fbb,
      definitions__,
      frames__);
}

struct TreeDebugRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TreeDebugRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MONSTERID = 4
  };
  int64_t monsterId() const {
    return GetField<int64_t>(VT_MONSTERID, -1LL);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_MONSTERID) &&
           verifier.EndTable();
  }
};

struct TreeDebugRequestBuilder {
  typedef TreeDebugRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_monsterId(int64_t monsterId) {
    fbb_.AddElement<int64_t>(TreeDebugRequest::VT_MONSTERID, monsterId, -1LL);
  }
  explicit TreeDebugRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TreeDebugRequestBuilder &operator=(const TreeDebugRequestBuilder &);
  flatbuffers::Offset<TreeDebugRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TreeDebugRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<TreeDebugRequest> CreateTreeDebugRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    int64_t monsterId = -1LL) {
  TreeDebugRequestBuilder builder_(_fbb);
  builder_.add_monsterId(monsterId);
  return builder_.Finish();
}

struct EnterGate FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EnterGateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAPID = 4,
    VT_GATEID = 6,
    VT_POS = 8,
    VT_AGENTID = 10
  };
  int32_t mapId() const {
    return GetField<int32_t>(VT_MAPID, 0);
  }
  int32_t gateId() const {
    return GetField<int32_t>(VT_GATEID, 0);
  }
  const syncnet::Vec3 *pos() const {
    return GetStruct<const syncnet::Vec3 *>(VT_POS);
  }
  int32_t agentId() const {
    return GetField<int32_t>(VT_AGENTID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MAPID) &&
           VerifyField<int32_t>(verifier, VT_GATEID) &&
           VerifyField<syncnet::Vec3>(verifier, VT_POS) &&
           VerifyField<int32_t>(verifier, VT_AGENTID) &&
           verifier.EndTable();
  }
};

struct EnterGateBuilder {
  typedef EnterGate Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_mapId(int32_t mapId) {
    fbb_.AddElement<int32_t>(EnterGate::VT_MAPID, mapId, 0);
  }
  void add_gateId(int32_t gateId) {
    fbb_.AddElement<int32_t>(EnterGate::VT_GATEID, gateId, 0);
  }
  void add_pos(const syncnet::Vec3 *pos) {
    fbb_.AddStruct(EnterGate::VT_POS, pos);
  }
  void add_agentId(int32_t agentId) {
    fbb_.AddElement<int32_t>(EnterGate::VT_AGENTID, agentId, 0);
  }
  explicit EnterGateBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  EnterGateBuilder &operator=(const EnterGateBuilder &);
  flatbuffers::Offset<EnterGate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<EnterGate>(end);
    return o;
  }
};

inline flatbuffers::Offset<EnterGate> CreateEnterGate(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t mapId = 0,
    int32_t gateId = 0,
    const syncnet::Vec3 *pos = 0,
    int32_t agentId = 0) {
  EnterGateBuilder builder_(_fbb);
  builder_.add_agentId(agentId);
  builder_.add_pos(pos);
  builder_.add_gateId(gateId);
  builder_.add_mapId(mapId);
  return builder_.Finish();
}

inline bool VerifyGameMessages(flatbuffers::Verifier &verifier, const void *obj, GameMessages type) {
  switch (type) {
    case GameMessages_NONE: {
      return true;
    }
    case GameMessages_AddAgent: {
      auto ptr = reinterpret_cast<const syncnet::AddAgent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_RemoveAgent: {
      auto ptr = reinterpret_cast<const syncnet::RemoveAgent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_SetMoveTarget: {
      auto ptr = reinterpret_cast<const syncnet::SetMoveTarget *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_ActorInfo: {
      auto ptr = reinterpret_cast<const syncnet::ActorInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_UpdateActorNotify: {
      auto ptr = reinterpret_cast<const syncnet::UpdateActorNotify *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_Ping: {
      auto ptr = reinterpret_cast<const syncnet::Ping *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_SetRaycast: {
      auto ptr = reinterpret_cast<const syncnet::SetRaycast *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_Login: {
      auto ptr = reinterpret_cast<const syncnet::Login *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_UseSkill: {
      auto ptr = reinterpret_cast<const syncnet::UseSkill *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_TreeDebugSync: {
      auto ptr = reinterpret_cast<const syncnet::TreeDebugSync *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_EnterGate: {
      auto ptr = reinterpret_cast<const syncnet::EnterGate *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GameMessages_TreeDebugRequest: {
      auto ptr = reinterpret_cast<const syncnet::TreeDebugRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyGameMessagesVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyGameMessages(
        verifier,  values->Get(i), types->GetEnum<GameMessages>(i))) {
      return false;
    }
  }
  return true;
}

inline const syncnet::GameMessage *GetGameMessage(const void *buf) {
  return flatbuffers::GetRoot<syncnet::GameMessage>(buf);
}

inline const syncnet::GameMessage *GetSizePrefixedGameMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<syncnet::GameMessage>(buf);
}

inline bool VerifyGameMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<syncnet::GameMessage>(nullptr);
}

inline bool VerifySizePrefixedGameMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<syncnet::GameMessage>(nullptr);
}

inline void FinishGameMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<syncnet::GameMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGameMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<syncnet::GameMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace syncnet

#endif  // FLATBUFFERS_GENERATED_SYNCNET_SYNCNET_H_
