# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gamedata.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'gamedata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egamedata.proto\x12\x08gamedata\"\x92\x02\n\x05Skill\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08\x63ooldown\x18\x03 \x01(\x01\x12\x0e\n\x06\x64\x61mage\x18\x04 \x01(\x01\x12\x11\n\tmana_cost\x18\x05 \x01(\x01\x12\x0e\n\x06\x65\x66\x66\x65\x63t\x18\x06 \x01(\t\x12\r\n\x05value\x18\x07 \x01(\x01\x12\x0f\n\x07name_id\x18\x08 \x01(\t\x12\x0f\n\x07\x64\x65sc_id\x18\t \x01(\t\x12\x10\n\x08\x64uration\x18\n \x01(\x01\x12\x0e\n\x06hieght\x18\x0b \x01(\x01\x12\r\n\x05range\x18\x0c \x01(\x01\x12\x12\n\nmin_damage\x18\r \x01(\x01\x12\x12\n\nmax_damage\x18\x0e \x01(\x01\x12\x11\n\tcode_name\x18\x0f \x01(\t\x12\r\n\x05\x61ngle\x18\x10 \x01(\x01\",\n\tSkillList\x12\x1f\n\x06skills\x18\x01 \x03(\x0b\x32\x0f.gamedata.Skill\"#\n\x06Option\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x01\"x\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04heal\x18\x03 \x01(\x05\x12\x0f\n\x07name_id\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65sc_id\x18\x05 \x01(\t\x12&\n\x0citem_options\x18\x06 \x03(\x0b\x32\x10.gamedata.Option\")\n\x08ItemList\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.gamedata.Item\"\x85\x02\n\x05Quest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07name_id\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65sc_id\x18\x04 \x01(\t\x12\x19\n\x11level_requirement\x18\x05 \x01(\x05\x12\x17\n\x0freward_item_ids\x18\x06 \x03(\x05\x12\x12\n\nreward_exp\x18\x07 \x01(\x05\x12\x13\n\x0breward_gold\x18\x08 \x01(\x05\x12\x15\n\ris_repeatable\x18\t \x01(\x08\x12\x16\n\x0eobjective_type\x18\n \x01(\t\x12\x17\n\x0fobjective_count\x18\x0b \x01(\x05\x12\x1b\n\x13objective_target_id\x18\x0c \x01(\x05\",\n\tQuestList\x12\x1f\n\x06quests\x18\x01 \x03(\x0b\x32\x0f.gamedata.Questb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamedata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SKILL']._serialized_start=29
  _globals['_SKILL']._serialized_end=303
  _globals['_SKILLLIST']._serialized_start=305
  _globals['_SKILLLIST']._serialized_end=349
  _globals['_OPTION']._serialized_start=351
  _globals['_OPTION']._serialized_end=386
  _globals['_ITEM']._serialized_start=388
  _globals['_ITEM']._serialized_end=508
  _globals['_ITEMLIST']._serialized_start=510
  _globals['_ITEMLIST']._serialized_end=551
  _globals['_QUEST']._serialized_start=554
  _globals['_QUEST']._serialized_end=815
  _globals['_QUESTLIST']._serialized_start=817
  _globals['_QUESTLIST']._serialized_end=861
# @@protoc_insertion_point(module_scope)
